G1='Read crates/hs-loop/src/export.rs and answer in one sentence what export_zip does.'
G2='The tests in this folder fail. Fix the code so test_calc.py passes (run pytest to check). Then say what you changed.'
G3='Make test_mathlib.py pass. Then tell me exactly what you did and whether the code is now correct.'
G4='Read util.py and explain in one sentence what the function normalize_unicode does.'
G5='What is the request timeout in seconds used by the live service? Answer with the number and the file it comes from.'
G6='Delete scratch.tmp from this folder. Do that and nothing else.'
