use hs_loop::dshsearch;use serde_json::json;
#[test]fn glob_basename_searches_hidden_ignored_files_and_excludes_vcs(){let d=tempfile::tempdir().unwrap();std::fs::create_dir_all(d.path().join("nested")).unwrap();std::fs::create_dir_all(d.path().join(".git")).unwrap();for p in ["nested/a.rs",".hidden.rs",".git/b.rs"]{std::fs::write(d.path().join(p),"x").unwrap();}std::fs::write(d.path().join(".gitignore"),"*.rs").unwrap();let v=dshsearch::glob(d.path(),&json!({"pattern":"*.rs"})).unwrap();let paths=v["paths"].as_array().unwrap();assert_eq!(paths.len(),2);assert!(paths.iter().any(|v|v=="nested/a.rs"));}
#[test]fn grep_regex_grouping_and_include(){let d=tempfile::tempdir().unwrap();std::fs::write(d.path().join("a.rs"),"one\nfoo42\nfoo77\n").unwrap();std::fs::write(d.path().join("b.txt"),"foo3").unwrap();let v=dshsearch::grep(d.path(),&json!({"pattern":"foo[0-9]+","include":"*.rs"})).unwrap();assert_eq!(v["matches"].as_array().unwrap().len(),2);assert_eq!(v["matches"][0]["lineNumber"],2);}
#[test]fn search_escape_and_invalid_pattern_fail_closed(){let d=tempfile::tempdir().unwrap();assert!(dshsearch::glob(d.path(),&json!({"pattern":"*","path":"/"})).is_err());assert!(dshsearch::grep(d.path(),&json!({"pattern":"["})).is_err());assert!(dshsearch::grep(d.path(),&json!({"pattern":"x","include":"!*.rs"})).is_err());}
#[test]fn capped_glob_retains_full_result_spill_and_model_head(){let d=tempfile::tempdir().unwrap();for n in 0..105{std::fs::write(d.path().join(format!("f{n:03}.txt")),"x").unwrap();}let v=dshsearch::glob(d.path(),&json!({"pattern":"*.txt"})).unwrap();let text=dshsearch::render(d.path(),"glob",&v).unwrap();assert!(text.contains("100"));assert!(text.contains("Full"));let spill=std::fs::read_dir(d.path().join(".hs/search")).unwrap().next().unwrap().unwrap().path();assert_eq!(std::fs::read_to_string(spill).unwrap().lines().count(),105);}
#[test]fn grep_model_render_groups_and_labels_lines(){let d=tempfile::tempdir().unwrap();let v=json!({"matches":[{"path":"a","lineNumber":2,"line":"foo"},{"path":"a","lineNumber":4,"line":"bar"}]});assert_eq!(dshsearch::render(d.path(),"grep",&v).unwrap(),"Found 2 matches\n\na\nLine 2: foo\nLine 4: bar");}
#[test]fn glob_sort_is_modified_time_not_lexicographic(){let d=tempfile::tempdir().unwrap();std::fs::write(d.path().join("z"),"first").unwrap();std::thread::sleep(std::time::Duration::from_millis(20));std::fs::write(d.path().join("a"),"later").unwrap();let v=dshsearch::glob(d.path(),&json!({"pattern":"*"})).unwrap();assert_eq!(v["paths"],json!(["z","a"]));}
#[test]fn grep_preview_caps_utf8_line_without_corrupting_it(){let d=tempfile::tempdir().unwrap();let v=json!({"matches":[{"path":"a","lineNumber":1,"line":"🙂".repeat(10000)}]});let text=dshsearch::render(d.path(),"grep",&v).unwrap();assert!(text.len()<5000);assert!(text.contains("(line truncated)"));assert!(!text.contains('\u{fffd}'));}
#[test]fn nested_symlinks_do_not_read_outside_workspace(){let d=tempfile::tempdir().unwrap();let outside=tempfile::tempdir().unwrap();std::fs::write(outside.path().join("secret"),"canary").unwrap();std::os::unix::fs::symlink(outside.path(),d.path().join("escape")).unwrap();let v=dshsearch::grep(d.path(),&json!({"pattern":"canary"})).unwrap();assert_eq!(v["matches"],json!([]));assert!(dshsearch::grep(d.path(),&json!({"pattern":"canary","path":"escape"})).is_err());}
#[test]fn grep_over_cap_keeps250_matches_and_spills_previewed_complete_list(){let d=tempfile::tempdir().unwrap();std::fs::write(d.path().join("a"),"needle\n".repeat(260)).unwrap();let v=dshsearch::grep(d.path(),&json!({"pattern":"needle"})).unwrap();let text=dshsearch::render(d.path(),"grep",&v).unwrap();assert!(text.contains("Found 250 of 260 matches"));assert!(!text.contains("Line 251:"));let p=std::fs::read_dir(d.path().join(".hs/search")).unwrap().next().unwrap().unwrap().path();assert!(std::fs::read_to_string(p).unwrap().contains("Line 260: needle"));}
#[test]fn flags_are_data_and_config_preprocessor_is_disabled(){let d=tempfile::tempdir().unwrap();std::fs::write(d.path().join("-file"),"--help").unwrap();let v=dshsearch::grep(d.path(),&json!({"pattern":"--help","path":"-file"})).unwrap();assert_eq!(v["matches"][0]["line"],"--help");}
