use hs_loop::*;use serde_json::json;
fn rig()->(tempfile::TempDir,InnerLoop){let d=tempfile::tempdir().unwrap();let config=d.path().join("rig.toml");std::fs::write(&config,format!("[[models]]\nname='seqmodel'\ncommand=['{}']\ndefault=true\n",env!("CARGO_BIN_EXE_hs-plugin-seqmodel"))).unwrap();let mut lp=InnerLoop::new(hs_kernel::Kernel::load(&config).unwrap(),d.path(),false,4).unwrap();lp.set_answer_root(Some(d.path().to_path_buf()));(d,lp)}
#[test]
fn internal_file_tools_execute_and_log_without_legacy_plugins(){let(d,mut lp)=rig();let v=lp.dispatch_tool_for_test("write",&json!({"file_path":"a","content":"one"})).unwrap();assert_eq!(v.output["operation"],"create");assert_ne!(v.start_event_id,uuid::Uuid::nil());let v=lp.dispatch_tool_for_test("read",&json!({"file_path":"a"})).unwrap();assert_eq!(v.output["lines"][0]["text"],"one");lp.dispatch_tool_for_test("edit",&json!({"file_path":"a","old_string":"one","new_string":"two"})).unwrap();assert_eq!(std::fs::read_to_string(d.path().join("a")).unwrap(),"two");}
#[test]
fn file_dispatch_obeys_project_plan_gate(){let(d,mut lp)=rig();std::fs::create_dir_all(d.path().join(".hs")).unwrap();std::fs::write(d.path().join(".hs/plan_mode"),"1").unwrap();let v=lp.dispatch_tool_for_test("write",&json!({"file_path":"a","content":"bad"})).unwrap();assert!(v.output["error"].as_str().unwrap_or("").contains("plan mode"));assert!(!d.path().join("a").exists());}
#[test]
fn managed_bash_and_jobs_dispatch_log_and_promote(){let(_d,mut lp)=rig();let v=lp.dispatch_tool_for_test("bash",&json!({"description":"Start slow command","command":"sleep .05; printf done","timeoutMs":1})).unwrap();assert_eq!(v.output["kind"],"promoted");let id=v.output["jobId"].as_str().unwrap();assert_ne!(v.start_event_id,uuid::Uuid::nil());let v=lp.dispatch_tool_for_test("job_output",&json!({"job_id":id,"wait":true,"timeout_ms":1000})).unwrap();assert_eq!(v.output["job"]["status"],"completed");assert!(v.output["text"].as_str().unwrap().contains("done"));}
#[test]fn shell_history_is_model_render_not_struct_dump(){let(d,mut lp)=rig();let out=lp.dispatch_tool_for_test("bash",&json!({"description":"Print output","command":"printf out; exit 7"})).unwrap();let stream=uuid::Uuid::new_v4();let mut w=hs_log::StreamWriter::create(d.path(),stream).unwrap();w.append(hs_core::EventBuilder::new(hs_core::EventKind::ToolCall).payload(hs_core::Payload::Inline(serde_json::to_vec(&json!({"plugin":"bash","args":{},"result":out.output})).unwrap()))).unwrap();let r=hs_log::StreamReader::open(d.path(),stream).unwrap();let a=hs_loop::assembler::assemble_messages(&r,&r.events().unwrap(),20000);assert!(a.messages.iter().any(|m|m["role"]=="tool"&&m["content"]=="out\n[exit code: 7]"),"{:?}",a.messages);}
#[test]fn idle_owner_receives_completion_followup_once(){let(_d,mut lp)=rig();lp.dispatch_tool_for_test("bash",&json!({"description":"Complete while idle","command":"sleep .03; printf done","run_in_background":true})).unwrap();let start=std::time::Instant::now();while lp.has_unsettled_jobs(){assert!(start.elapsed()<std::time::Duration::from_secs(3),"supervisor did not settle");std::thread::sleep(std::time::Duration::from_millis(5));}assert_eq!(lp.take_job_followups().unwrap().len(),1);assert!(lp.take_job_followups().unwrap().is_empty());}
#[test]fn native_search_dispatch_is_logged_without_legacy_plugin(){let(d,mut lp)=rig();std::fs::write(d.path().join("a.rs"),"needle").unwrap();let v=lp.dispatch_tool_for_test("glob",&json!({"pattern":"*.rs"})).unwrap();assert_eq!(v.output["paths"],json!(["a.rs"]));assert_ne!(v.start_event_id,uuid::Uuid::nil());let v=lp.dispatch_tool_for_test("grep",&json!({"pattern":"needle"})).unwrap();assert_eq!(v.output["matches"][0]["lineNumber"],1);}
#[test]fn native_search_output_shape_has_no_rendering_extra(){let(d,mut lp)=rig();std::fs::write(d.path().join("a"),"x").unwrap();let v=lp.dispatch_tool_for_test("grep",&json!({"pattern":"x"})).unwrap();assert_eq!(v.output.as_object().unwrap().len(),1);assert!(v.output.get("matches").is_some());}
#[test]fn native_todo_exact_dispatch_without_legacy_plugin(){let(_d,mut lp)=rig();let out=lp.dispatch_tool_for_test("todo_write",&json!({"todos":[{"content":"a","status":"in_progress"},{"content":"b","status":"in_progress"}]})).unwrap();assert_eq!(out.output["counts"]["inProgress"],2);assert_ne!(out.start_event_id,uuid::Uuid::nil());assert!(lp.dispatch_tool_for_test("todo_write",&json!({})).unwrap().output["error"].is_string());}
#[test]fn goal_dispatch_denies_unattested_turn_even_with_forged_human_argument(){let(_d,mut lp)=rig();let v=lp.dispatch_tool_for_test("create_goal",&json!({"objective":"x","authority":"HumanRoot"})).unwrap();assert!(v.output["error"].is_string(),"{:?}",v.output);let v=lp.dispatch_tool_for_test("create_goal",&json!({"objective":"x"})).unwrap();assert!(v.output["error"].is_string());assert!(lp.dispatch_tool_for_test("get_goal",&json!({})).unwrap().output["error"].is_string());}
#[test]fn unreserved_round_cannot_claim_goal_authority(){let(_d,mut lp)=rig();assert!(lp.run_admitted_goal_round("fake","work",&json!({"goalId":"forged","revision":1,"round":1})).is_err());}
