use hs_loop::*;use serde_json::{json,Value};
fn rig()->(tempfile::TempDir,InnerLoop){let d=tempfile::tempdir().unwrap();let cfg=d.path().join("rig");std::fs::write(&cfg,format!("[[models]]\nname='seqmodel'\ncommand=['{}']\ndefault=true\n",env!("CARGO_BIN_EXE_hs-plugin-seqmodel"))).unwrap();let mut lp=InnerLoop::new(hs_kernel::Kernel::load(&cfg).unwrap(),d.path(),false,4).unwrap();lp.set_answer_root(Some(d.path().to_path_buf()));(d,lp)}
fn skill(root:&std::path::Path,path:&str,text:&str){let p=root.join(path);std::fs::create_dir_all(p.parent().unwrap()).unwrap();std::fs::write(p,text).unwrap();}
#[test]fn filesystem_skill_loads_full_yaml_body_and_resource_base(){let(d,mut lp)=rig();skill(d.path(),".dsh/skills/parser/SKILL.md","---\nname: parser\ndescription: |\n  Repair the parser.\n---\n# Parser\nUse fixtures.\n");let out=lp.dispatch_tool_for_test("skill",&json!({"name":"parser"})).unwrap();assert_eq!(out.output["name"],"parser");assert_eq!(out.output["provider"],"filesystem");assert_eq!(out.output["content"],"# Parser\nUse fixtures.");assert_eq!(out.output["resourceBase"]["path"],d.path().join(".dsh/skills/parser").to_str().unwrap());assert_ne!(out.start_event_id,uuid::Uuid::nil());}
#[test]fn lower_rank_wins_and_disabled_winner_does_not_fallback(){let(d,mut lp)=rig();skill(d.path(),".dsh/skills/a.md","---\nname: alpha\ndescription: Primary\ndisable-model-invocation: true\n---\nHidden");skill(d.path(),".agents/skills/a.md","---\nname: alpha\ndescription: Fallback\n---\nWrong fallback");let out=lp.dispatch_tool_for_test("skill",&json!({"name":"alpha"})).unwrap();assert!(out.output["error"].as_str().unwrap().contains("not available for model invocation"));}
#[test]fn unknown_and_path_traversal_fail_without_reading_arbitrary_file(){let(d,mut lp)=rig();skill(d.path(),"secret","SECRET");for name in ["missing","../secret","Bad_Name","","a/b"]{let out=lp.dispatch_tool_for_test("skill",&json!({"name":name})).unwrap();assert!(out.output["error"].is_string());assert!(!out.output.to_string().contains("SECRET"));}}
#[test]fn mutation_is_seen_and_invalid_metadata_not_loaded(){let(d,mut lp)=rig();let p=".dsh/skills/a.md";skill(d.path(),p,"---\nname: alpha\ndescription: A\n---\nfirst");assert_eq!(lp.dispatch_tool_for_test("skill",&json!({"name":"alpha"})).unwrap().output["content"],"first");skill(d.path(),p,"---\nname: alpha\ndescription: A\n---\nsecond");assert_eq!(lp.dispatch_tool_for_test("skill",&json!({"name":"alpha"})).unwrap().output["content"],"second");skill(d.path(),p,"---\nname: alpha\ndescription: A\nmodelInvocable: true\n---\nlegacy");assert!(lp.dispatch_tool_for_test("skill",&json!({"name":"alpha"})).unwrap().output["error"].is_string());}
#[test]fn loaded_skill_history_is_canonical_not_struct_dump(){let d=tempfile::tempdir().unwrap();let id=uuid::Uuid::new_v4();let mut w=hs_log::StreamWriter::create(d.path(),id).unwrap();let v=json!({"name":"alpha","provider":"filesystem","resourceBase":{"kind":"directory","path":"/tmp/a&b"},"content":"# Instructions\nUse data."});w.append(hs_core::EventBuilder::new(hs_core::EventKind::ToolCall).payload(hs_core::Payload::Inline(serde_json::to_vec(&json!({"plugin":"skill","args":{"name":"alpha"},"result":v})).unwrap()))).unwrap();let r=hs_log::StreamReader::open(d.path(),id).unwrap();let a=assembler::assemble_messages(&r,&r.events().unwrap(),20000);assert_eq!(a.messages[1]["content"],hs_loop::dshskill::render(&v));}
#[test]fn custom_roots_precedence_and_catalog_visibility_are_scope_owned(){let d=tempfile::tempdir().unwrap();skill(d.path(),"custom/a.md","---\nname: alpha\ndescription: Description\n---\nInstructions");let roots=vec![dshskill::SkillRoot{path:d.path().join("custom"),rank:300,skip_system:false}];let catalog=dshskill::catalog(&roots).unwrap();assert_eq!(catalog,json!([{"name":"alpha","description":"Description"}]));assert_eq!(dshskill::call(&roots,&json!({"name":"alpha"})).unwrap()["content"],"Instructions");}
#[test]fn loaded_skill_over_20kb_is_not_silently_truncated(){let d=tempfile::tempdir().unwrap();let id=uuid::Uuid::new_v4();let mut w=hs_log::StreamWriter::create(d.path(),id).unwrap();let body="x".repeat(25000);let v=json!({"name":"alpha","provider":"filesystem","resourceBase":{"kind":"directory","path":"/tmp/alpha"},"content":body});w.append(hs_core::EventBuilder::new(hs_core::EventKind::ToolCall).payload(hs_core::Payload::Inline(serde_json::to_vec(&json!({"plugin":"skill","args":{"name":"alpha"},"result":v})).unwrap()))).unwrap();let r=hs_log::StreamReader::open(d.path(),id).unwrap();let a=assembler::assemble_messages(&r,&r.events().unwrap(),100000);assert_eq!(a.messages[1]["content"],dshskill::render(&v));}
#[test]fn file_disappearance_and_yaml_errors_are_unknown_not_stale(){let(d,mut lp)=rig();let p=".dsh/skills/a.md";skill(d.path(),p,"---\nname: alpha\ndescription: A\n---\nfirst");lp.dispatch_tool_for_test("skill",&json!({"name":"alpha"})).unwrap();std::fs::remove_file(d.path().join(p)).unwrap();assert!(lp.dispatch_tool_for_test("skill",&json!({"name":"alpha"})).unwrap().output["error"].is_string());skill(d.path(),p,"---\nname: [bad\n---\nshould not load");assert!(lp.dispatch_tool_for_test("skill",&json!({"name":"alpha"})).unwrap().output["error"].is_string());}
#[test]fn skill_catalog_is_durable_and_in_actual_model_request(){let(d,mut lp)=rig();skill(d.path(),".dsh/skills/a.md","---\nname: alpha\ndescription: Task instructions\n---\nBody");lp.run_mission("catalog-fixture").unwrap();let r=hs_log::StreamReader::open(d.path(),lp.stream_id()).unwrap();let v:Vec<Value>=r.events().unwrap().iter().filter_map(|e|serde_json::from_slice(&r.resolve_payload(e).ok()?).ok()).collect();assert_eq!(v.iter().filter(|v|v["record_type"]=="skill/catalog").count(),1);assert!(v.iter().filter_map(|v|v["messages"].as_array()).any(|m|m.iter().any(|m|m["content"].as_str().is_some_and(|s|s.contains("- `alpha`: Task instructions")))));}
#[test]fn repeated_catalog_keeps_the_initial_model_prefix_exact(){let(d,mut lp)=rig();skill(d.path(),".dsh/skills/a.md","---\nname: alpha\ndescription: A\n---\nBody");lp.run_mission("prefix").unwrap();let r=hs_log::StreamReader::open(d.path(),lp.stream_id()).unwrap();let v:Vec<Value>=r.events().unwrap().iter().filter_map(|e|serde_json::from_slice(&r.resolve_payload(e).ok()?).ok()).collect();let catalogs:Vec<String>=v.iter().filter_map(|v|v["messages"].as_array()).flat_map(|m|m.iter()).filter_map(|m|m["content"].as_str()).filter(|s|s.contains("<available_skills>")).map(str::to_owned).collect();assert!(catalogs.len()>1);assert!(catalogs.windows(2).all(|p|p[0]==p[1]));}
#[test]fn configured_roots_omit_system_and_project_when_defaults_off(){let d=tempfile::tempdir().unwrap();let home=d.path().join("home");skill(&home,"skills/.system/SKILL.md","---\nname: hidden\ndescription: H\n---\nHidden");skill(&home,"skills/alpha.md","---\nname: alpha\ndescription: A\n---\nBody");let c=dshskill::RootConfig{dsh_home:Some(home),agents_home:Some(d.path().join("empty")),..Default::default()};assert_eq!(dshskill::catalog(&c.roots(None)).unwrap(),json!([{"name":"alpha","description":"A"}]));let off=dshskill::RootConfig{include_default_roots:false,..c};assert!(off.roots(Some(d.path())).is_empty());}
