use hs_loop::dshtools::FileSession;use serde_json::json;
#[test]
fn schemas_match_wire(){let fixture:serde_json::Value=serde_json::from_str(include_str!("../../../artifacts/tool-diff/dsh-wire-tools.json")).unwrap();for n in ["write","edit"]{assert_eq!(hs_loop::dshtools::schema(n).unwrap(),fixture["tools"].as_array().unwrap().iter().find(|t|t["name"]==n).unwrap().clone());}}
#[test]
fn write_creates_but_cannot_clobber_unread_file(){let d=tempfile::tempdir().unwrap();let mut s=FileSession::new(d.path());s.write(&json!({"file_path":"a","content":"one"})).unwrap();assert_eq!(std::fs::read_to_string(d.path().join("a")).unwrap(),"one");let mut other=FileSession::new(d.path());assert!(other.write(&json!({"file_path":"a","content":"bad"})).is_err());assert_eq!(std::fs::read_to_string(d.path().join("a")).unwrap(),"one");}
#[test]
fn read_then_write_and_stale_guards(){let d=tempfile::tempdir().unwrap();std::fs::write(d.path().join("a"),"one").unwrap();let mut s=FileSession::new(d.path());s.read(&json!({"file_path":"a"})).unwrap();s.write(&json!({"file_path":"a","content":"two"})).unwrap();std::fs::write(d.path().join("a"),"external").unwrap();assert!(s.write(&json!({"file_path":"a","content":"bad"})).is_err());assert_eq!(std::fs::read_to_string(d.path().join("a")).unwrap(),"external");}
#[test]
fn edit_unique_all_and_noop_errors(){let d=tempfile::tempdir().unwrap();std::fs::write(d.path().join("a"),"x x").unwrap();let mut s=FileSession::new(d.path());assert!(s.edit(&json!({"file_path":"a","old_string":"x","new_string":"y"})).is_err());s.read(&json!({"file_path":"a"})).unwrap();assert!(s.edit(&json!({"file_path":"a","old_string":"x","new_string":"y"})).is_err());s.edit(&json!({"file_path":"a","old_string":"x","new_string":"y","replace_all":true})).unwrap();assert_eq!(std::fs::read_to_string(d.path().join("a")).unwrap(),"y y");for (a,b) in [("","z"),("y","y"),("missing","z")]{assert!(s.edit(&json!({"file_path":"a","old_string":a,"new_string":b})).is_err());}}
#[test]
fn edit_restores_crlf_and_deletes_literal(){let d=tempfile::tempdir().unwrap();std::fs::write(d.path().join("a"),"one\r\ntwo\r\n").unwrap();let mut s=FileSession::new(d.path());s.read(&json!({"file_path":"a"})).unwrap();s.edit(&json!({"file_path":"a","old_string":"one\ntwo","new_string":"three\nfour"})).unwrap();assert_eq!(std::fs::read_to_string(d.path().join("a")).unwrap(),"three\r\nfour\r\n");s.edit(&json!({"file_path":"a","old_string":"three\n","new_string":""})).unwrap();assert_eq!(std::fs::read_to_string(d.path().join("a")).unwrap(),"four\r\n");}
#[test]
fn invalid_and_escalation_args_do_not_mutate(){let d=tempfile::tempdir().unwrap();let mut s=FileSession::new(d.path());for v in [json!({"file_path":"a","content":3}),json!({"file_path":"../escape","content":"bad"}),json!({"file_path":"a","content":"bad","sandbox_permissions":"danger-full-access","justification":"do it"}),json!({"file_path":"a","content":"bad","extra":1})]{assert!(s.write(&v).is_err());}assert!(!d.path().join("a").exists());}
#[cfg(unix)]
#[test]
fn mode_preserved_and_symlink_escape_denied(){use std::os::unix::fs::PermissionsExt;let d=tempfile::tempdir().unwrap();std::fs::write(d.path().join("a"),"one").unwrap();std::fs::set_permissions(d.path().join("a"),std::fs::Permissions::from_mode(0o640)).unwrap();let mut s=FileSession::new(d.path());s.read(&json!({"file_path":"a"})).unwrap();s.write(&json!({"file_path":"a","content":"two"})).unwrap();assert_eq!(std::fs::metadata(d.path().join("a")).unwrap().permissions().mode() & 0o777,0o640);let outside=tempfile::tempdir().unwrap();std::os::unix::fs::symlink(outside.path(),d.path().join("link")).unwrap();assert!(s.write(&json!({"file_path":"link/a","content":"bad"})).is_err());assert!(!outside.path().join("a").exists());}
#[test]
fn write_and_edit_return_before_after_for_rendering(){let d=tempfile::tempdir().unwrap();let mut s=FileSession::new(d.path());let v=s.write(&json!({"file_path":"a","content":"one"})).unwrap();assert!(v["before"].is_null());assert_eq!(v["after"],"one");let v=s.edit(&json!({"file_path":"a","old_string":"one","new_string":"two"})).unwrap();assert_eq!(v["before"],"one");assert_eq!(v["after"],"two");let v=s.write(&json!({"file_path":"a","content":"three"})).unwrap();assert_eq!(v["before"],"two");assert_eq!(v["after"],"three");}
#[test]
fn file_mutations_are_classified_by_permission_and_plan_gates(){for n in ["write","edit"]{assert!(hs_loop::plan_mode::mutates(n,&json!({})));}assert!(!hs_loop::plan_mode::mutates("read",&json!({})));}
#[test]
fn creates_missing_parent_dirs_inside_project(){let d=tempfile::tempdir().unwrap();let mut s=FileSession::new(d.path());s.write(&json!({"file_path":"nested/deep/a","content":"one"})).unwrap();assert_eq!(std::fs::read_to_string(d.path().join("nested/deep/a")).unwrap(),"one");assert!(s.write(&json!({"file_path":"nested/../../../outside","content":"bad"})).is_err());}
#[test]
fn symlink_inside_project_points_to_real_file_without_replacing_link(){#[cfg(unix)]{let d=tempfile::tempdir().unwrap();std::fs::write(d.path().join("a"),"one").unwrap();std::os::unix::fs::symlink("a",d.path().join("link")).unwrap();let mut s=FileSession::new(d.path());s.read(&json!({"file_path":"link"})).unwrap();s.edit(&json!({"file_path":"link","old_string":"one","new_string":"two"})).unwrap();assert_eq!(std::fs::read_to_string(d.path().join("a")).unwrap(),"two");assert!(std::fs::symlink_metadata(d.path().join("link")).unwrap().file_type().is_symlink());}}
