use hs_loop::dshjobs::JobSession;use serde_json::json;
#[test]
fn four_exact_schemas_match_capture(){let f:serde_json::Value=serde_json::from_str(include_str!("../../../artifacts/tool-diff/dsh-wire-tools.json")).unwrap();for name in ["bash","job_list","job_output","job_kill"]{assert_eq!(hs_loop::dshtools::schema(name).unwrap(),f["tools"].as_array().unwrap().iter().find(|t|t["name"]==name).unwrap().clone());}}
#[test]
fn foreground_returns_separate_output_and_fresh_shell(){let d=tempfile::tempdir().unwrap();let mut s=JobSession::new(d.path());let v=s.bash(&json!({"description":"Print separate output","command":"export FOO=secret; printf out; printf err >&2"})).unwrap();assert_eq!(v["stdout"]["text"],"out");assert_eq!(v["stderr"]["text"],"err");let v=s.bash(&json!({"description":"Check fresh shell","command":"printf '%s' ${FOO-unset}"})).unwrap();assert_eq!(v["stdout"]["text"],"unset");}
#[test]
fn timeout_promotes_without_killing_and_output_is_incremental(){let d=tempfile::tempdir().unwrap();let mut s=JobSession::new(d.path());let v=s.bash(&json!({"description":"Run slow command","command":"printf first; sleep .15; printf second","timeoutMs":10})).unwrap();let id=v["jobId"].as_str().unwrap();assert_eq!(v["kind"],"promoted");let v=s.output(&json!({"job_id":id,"wait":true,"timeout_ms":1000})).unwrap();assert!(v["text"].as_str().unwrap().contains("second"));assert_eq!(v["job"]["status"],"completed");let v=s.output(&json!({"job_id":id})).unwrap();assert_eq!(v["text"],"");}
#[test]
fn background_wait_timeout_leaves_alive_and_kill_settles(){let d=tempfile::tempdir().unwrap();let mut s=JobSession::new(d.path());let v=s.bash(&json!({"description":"Start sleep job","command":"sleep 5","run_in_background":true})).unwrap();let id=v["jobId"].as_str().unwrap();let v=s.output(&json!({"job_id":id,"wait":true,"timeout_ms":1})).unwrap();assert_eq!(v["job"]["status"],"running");assert_eq!(s.kill(&json!({"job_id":id,"reason":"test complete"})).unwrap()["outcome"],"cancellation-requested");let v=s.output(&json!({"job_id":id,"wait":true,"timeout_ms":1000})).unwrap();assert_eq!(v["job"]["status"],"killed");}
#[test]
fn owner_isolation_and_job_id_traversal_denied(){let d=tempfile::tempdir().unwrap();let mut a=JobSession::new(d.path());let mut b=JobSession::new(d.path());let v=a.bash(&json!({"description":"Start own job","command":"true","run_in_background":true})).unwrap();let id=v["jobId"].as_str().unwrap();assert!(b.output(&json!({"job_id":id})).is_err());assert!(b.output(&json!({"job_id":"../../secret"})).is_err());assert_eq!(b.list(&json!({})).unwrap(),json!([]));}
#[test]
fn invalid_args_escalation_workdir_escape_fail_closed(){let d=tempfile::tempdir().unwrap();let mut s=JobSession::new(d.path());for a in [json!({"command":"true"}),json!({"description":"","command":"true"}),json!({"description":"test","command":"true","timeoutMs":0}),json!({"description":"test","command":"true","workdir":"/"}),json!({"description":"test","command":"true","sandbox_permissions":"danger-full-access","justification":"test"}),json!({"description":"test","command":"true","extra":1})]{assert!(s.bash(&a).is_err(),"{a}");}}

#[test]
fn large_output_is_bounded_and_full_stream_spills(){let d=tempfile::tempdir().unwrap();let mut s=JobSession::new(d.path());let v=s.bash(&json!({"description":"Print large output","command":"python3 -c 'print(\"x\"*100000)'"})).unwrap();assert_eq!(v["stdout"]["truncated"],true);assert!(v["stdout"]["text"].as_str().unwrap().len()<=30000);let p=v["stdout"]["spillPath"].as_str().unwrap();assert!(std::fs::metadata(p).unwrap().len()>100000);}
#[test]
fn spill_preparation_failure_does_not_launch_command(){let d=tempfile::tempdir().unwrap();std::fs::write(d.path().join(".hs"),"blocked").unwrap();let mut s=JobSession::new(d.path());assert!(s.bash(&json!({"description":"Must not launch","command":"touch marker"})).is_err());std::thread::sleep(std::time::Duration::from_millis(50));assert!(!d.path().join("marker").exists());}
#[test]
fn utf8_tail_never_invents_replacement_characters(){let d=tempfile::tempdir().unwrap();let mut s=JobSession::new(d.path());let v=s.bash(&json!({"description":"Print unicode output","command":"python3 -c 'print(\"🙂\"*10000,end=\"x\")'"})).unwrap();assert!(!v["stdout"]["text"].as_str().unwrap().contains('\u{fffd}'));}
#[test]
fn cancellation_settles_even_when_term_is_ignored(){let d=tempfile::tempdir().unwrap();let mut s=JobSession::new(d.path());let v=s.bash(&json!({"description":"Ignore gentle signal","command":"trap '' TERM; echo ready; sleep 5","run_in_background":true})).unwrap();let id=v["jobId"].as_str().unwrap();std::thread::sleep(std::time::Duration::from_millis(50));s.kill(&json!({"job_id":id})).unwrap();let v=s.output(&json!({"job_id":id,"wait":true,"timeout_ms":1500})).unwrap();assert_eq!(v["job"]["status"],"killed");}
#[test]
fn dropping_session_cancels_owned_background_work(){let d=tempfile::tempdir().unwrap();{let mut s=JobSession::new(d.path());s.bash(&json!({"description":"Start session job","command":"sleep .3; touch leaked","run_in_background":true})).unwrap();}std::thread::sleep(std::time::Duration::from_millis(400));assert!(!d.path().join("leaked").exists());}
#[test]
fn managed_environment_identifies_stable_session_without_ambient_values(){let d=tempfile::tempdir().unwrap();let mut s=JobSession::new(d.path());let cmd=json!({"description":"Read managed environment","command":"printf '%s|%s' \"$DSH_SHELL\" \"$DSH_SESSION_ID\""});let a=s.bash(&cmd).unwrap();let b=s.bash(&cmd).unwrap();assert!(a["stdout"]["text"].as_str().unwrap().starts_with("1|"));assert!(a["stdout"]["text"].as_str().unwrap().len()>20);assert_eq!(a["stdout"]["text"],b["stdout"]["text"]);}
#[test]
fn split_utf8_output_is_consumed_only_when_complete(){let d=tempfile::tempdir().unwrap();let mut s=JobSession::new(d.path());let v=s.bash(&json!({"description":"Write split utf8 bytes","command":"python3 -c 'import os,time;os.write(1,bytes([240,159]));time.sleep(.2);os.write(1,bytes([153,130]))'","run_in_background":true})).unwrap();let id=v["jobId"].as_str().unwrap();std::thread::sleep(std::time::Duration::from_millis(50));let first=s.output(&json!({"job_id":id})).unwrap();assert_eq!(first["text"],"");let last=s.output(&json!({"job_id":id,"wait":true,"timeout_ms":1000})).unwrap();assert_eq!(last["text"],"🙂");}
#[test]
fn completion_notice_once_unless_awaited_or_cancelled(){let d=tempfile::tempdir().unwrap();let mut s=JobSession::new(d.path());s.bash(&json!({"description":"Start quick job","command":"true","run_in_background":true})).unwrap();std::thread::sleep(std::time::Duration::from_millis(50));assert_eq!(s.notifications().len(),1);assert!(s.notifications().is_empty());let v=s.bash(&json!({"description":"Start awaited job","command":"sleep .05","run_in_background":true})).unwrap();s.output(&json!({"job_id":v["jobId"],"wait":true,"timeout_ms":1000})).unwrap();assert!(s.notifications().is_empty());}
#[test]
fn spill_directory_symlink_cannot_escape_root(){let d=tempfile::tempdir().unwrap();let outside=tempfile::tempdir().unwrap();std::os::unix::fs::symlink(outside.path(),d.path().join(".hs")).unwrap();let mut s=JobSession::new(d.path());assert!(s.bash(&json!({"description":"Reject spill escape","command":"touch launched"})).is_err());assert!(!d.path().join("launched").exists());assert_eq!(std::fs::read_dir(outside.path()).unwrap().count(),0);}
#[test]
fn foreground_signal_is_not_laundered_into_exit_code(){let d=tempfile::tempdir().unwrap();let mut s=JobSession::new(d.path());let v=s.bash(&json!({"description":"Signal self","command":"kill -TERM $$"})).unwrap();assert_eq!(v["signal"],"SIGTERM");assert!(v["exitCode"].is_null());}
#[test]fn completed_output_must_be_collected_before_final(){let d=tempfile::tempdir().unwrap();let mut s=JobSession::new(d.path());let v=s.bash(&json!({"description":"Start task","command":"printf result","run_in_background":true})).unwrap();std::thread::sleep(std::time::Duration::from_millis(50));assert_eq!(s.uncollected().len(),1);s.output(&json!({"job_id":v["jobId"],"wait":true})).unwrap();assert!(s.uncollected().is_empty());}
#[test]fn model_render_uses_dsh_status_and_foreground_markers(){assert_eq!(hs_loop::dshjobs::render("job_output",&json!({"text":"","job":{"status":"completed"}})),"(no new output)\n[status: completed]");assert_eq!(hs_loop::dshjobs::render("bash",&json!({"kind":"foreground","stdout":{"text":"out","truncated":false},"stderr":{"text":"err","truncated":false},"exitCode":7,"signal":null})),"out\n[stderr]\nerr\n[exit code: 7]");}
#[test]fn ordinary_exit_143_is_not_a_signal(){let d=tempfile::tempdir().unwrap();let mut s=JobSession::new(d.path());let v=s.bash(&json!({"description":"Exit ordinary code","command":"exit 143"})).unwrap();assert_eq!(v["exitCode"],143);assert!(v["signal"].is_null());}
#[test]fn framed_command_output_cannot_spoof_payload_status(){let d=tempfile::tempdir().unwrap();let mut s=JobSession::new(d.path());let v=s.bash(&json!({"description":"Print fake frame","command":"printf '%s' '{\"settled\":true,\"exit_code\":0,\"signal\":null}'; exit 7"})).unwrap();assert_eq!(v["exitCode"],7);assert!(v["stdout"]["text"].as_str().unwrap().contains("settled"));}
#[test]fn installer_includes_payload_status_supervisor(){assert!(include_str!("../../../install.sh").contains("hs-plugin-shell-supervisor"));assert!(include_str!("../../../.github/workflows/ab-run.yml").contains("target/debug/hs-plugin-*"));}
