//! Same-session goal domain. Authority is host-selected, never tool arguments.
use serde_json::{json,Value};
#[derive(Clone,Debug)]pub enum Authority{HumanRoot,External,GoalRound{id:String,revision:u64,round:u64}}
#[derive(Default,Clone)]pub struct GoalSession{goal:Option<Value>,armed:bool}
fn positive(v:&Value)->Result<u64,String>{v.as_u64().filter(|n|*n>0&&*n<=9007199254740991).ok_or_else(||"positive safe integer required".into())}
fn objective(v:&Value)->Result<String,String>{v.as_str().map(str::trim).filter(|s|!s.is_empty()).map(str::to_owned).ok_or_else(||"objective must be non-empty string".into())}
impl GoalSession{
 pub fn host_command(&mut self,raw:&str)->Result<Value,String>{let t=raw.trim();let lower=t.to_lowercase();if t.is_empty(){return Ok(self.view())}if lower=="edit"{return Err("Goal editing requires a replacement objective".into())}if lower=="clear"{self.goal=None;self.armed=false;return Ok(self.view())}if matches!(lower.as_str(),"pause"|"resume")||lower.starts_with("edit ")||lower.starts_with("edit\t"){
 let g=self.goal.as_ref().ok_or("No goal is currently set")?;let id=g["id"].clone();let rev=positive(&g["revision"])?;
 if lower=="resume"&&g["phase"]=="paused" {if g["roundsStarted"].as_u64().unwrap()>=g["maxGoalRounds"].as_u64().unwrap(){return Err("GOAL_INVALID_TRANSITION".into())}let mut next=g.clone();next["phase"]=json!("active");next["revision"]=json!(rev.checked_add(1).filter(|n|*n<=9007199254740991).ok_or("goal revision overflow")?);self.goal=Some(next);self.armed=true;return Ok(self.view())}
 let mut args=json!({"goal_id":id,"revision":rev,"action":if lower.starts_with("edit"){"edit"}else{lower.as_str()}});if lower.starts_with("edit"){args["objective"]=json!(t[4..].trim());}return self.call("update_goal",&args,Authority::HumanRoot)
 }self.call("create_goal",&json!({"objective":t}),Authority::HumanRoot)}
 pub fn disarm(&mut self){self.armed=false;}
 pub fn wrapup(&self,authority:&Authority)->Option<String>{if !matches!(authority,Authority::GoalRound{..}){return None}let g=self.goal.as_ref()?;if !matches!(g["phase"].as_str(),Some("complete"|"blocked")){return None}Some(format!("<goal_{}>\nObjective: {}\nWrite the closing message now with only outcomes and verification established in this session. Note any concrete blocking condition and what is needed. No further work tools: finish through the normal answer submission and independent verification path. This goal status is not a checker pass.\n</goal_{}>",g["phase"].as_str()?,g["objective"],g["phase"].as_str()?))}
 pub fn view(&self)->Value{match &self.goal{None=>json!({"goal":null}),Some(g)=>json!({"goal":g,"activation":if self.armed{"armed"}else{"disarmed"}})}}
 pub fn snapshot(&self)->Value{self.goal.clone().unwrap_or(Value::Null)}
 pub fn restore(v:Value)->Result<Self,String>{if v.is_null(){return Ok(Self::default())}let o=v.as_object().ok_or("invalid goal snapshot")?;for k in ["id","revision","objective","phase","roundsStarted","maxGoalRounds"]{if !o.contains_key(k){return Err("incomplete goal snapshot".into())}}if o.len()!=if v["phase"]=="blocked"{7}else{6}{return Err("invalid goal snapshot keys".into())}let id=v["id"].as_str().filter(|s|!s.is_empty()&&*s==s.trim()).ok_or("invalid goal id")?;let _=id;positive(&v["revision"])?;objective(&v["objective"])?;positive(&v["maxGoalRounds"])?;v["roundsStarted"].as_u64().filter(|n|*n<=9007199254740991).ok_or("invalid rounds")?;if !matches!(v["phase"].as_str(),Some("active"|"paused"|"blocked"|"complete")){return Err("invalid goal phase".into())}if v["phase"]=="blocked"&&(v["blockedReason"]["code"].as_str().is_none()||v["blockedReason"]["message"].as_str().is_none()||v["blockedReason"].as_object().is_none_or(|o|o.len()!=2)){return Err("invalid blocked reason".into())}Ok(Self{goal:Some(v),armed:false})}
 pub fn fold(events:&[Value])->Result<Self,String>{let mut state=Self::default();for event in events {let next=Self::restore(event["snapshot"].clone())?;let op=event["operation"].as_str().ok_or("missing goal operation")?;if op=="host"{let mut expected=state.clone();expected.host_command(event["input"].as_str().ok_or("invalid host goal input")?)?;let mut value=expected.snapshot();if (state.goal.is_none()||state.goal.as_ref().is_some_and(|g|g["phase"]=="complete"))&&value.is_object()&&value["revision"]==1{value["id"]=next.snapshot()["id"].clone();}if value!=next.snapshot(){return Err("invalid host goal replay".into())}state=next;continue;}if op=="round" {let mut expected=state.clone();expected.armed=true;let source=expected.admit_round()?;if expected.snapshot()!=next.snapshot()||event["source"]!=source.unwrap_or(Value::Null){return Err("invalid admitted round replay".into())}state=next;continue;}if op=="create_goal" {let goal=next.goal.as_ref().ok_or("missing created goal")?;if goal["revision"]!=1||goal["roundsStarted"]!=0||goal["phase"]!="active"||state.goal.as_ref().is_some_and(|g|g["phase"]!="complete"){return Err("invalid goal create replay".into())}let mut expected=state.clone();expected.call("create_goal",&event["args"],Authority::HumanRoot)?;let mut value=expected.snapshot();value["id"]=goal["id"].clone();if value!=next.snapshot(){return Err("invalid goal create snapshot".into())}}else if op=="update_goal" {let action=event["args"]["action"].as_str().unwrap_or("");let mut expected=state.clone();if action=="resume" {if expected.goal.as_ref().is_some_and(|g|g["phase"]=="paused"){return Err("paused model resume replay".into())}expected.armed=false;}expected.call("update_goal",&event["args"],Authority::HumanRoot)?;if expected.snapshot()!=next.snapshot(){return Err("invalid goal update snapshot".into())}}else{return Err("unknown goal replay operation".into())}state=next;}state.armed=false;Ok(state)}
 pub fn call(&mut self,tool:&str,a:&Value,authority:Authority)->Result<Value,String>{let allowed:&[&str]=match tool{"get_goal"=>&[],"create_goal"=>&["objective","max_goal_rounds"],"update_goal"=>&["goal_id","revision","action","objective","max_goal_rounds","blocked_reason"],_=>return Err("unknown goal tool".into())};let o=a.as_object().ok_or("arguments must be object")?;if o.keys().any(|k|!allowed.contains(&k.as_str())){return Err("unknown goal argument".into())}if tool=="get_goal"{return Ok(self.view())}let human=matches!(authority,Authority::HumanRoot);
 if tool=="create_goal"{if !human{return Err("this goal operation requires a direct human turn on a top-level agent".into())}let obj=objective(&a["objective"])?;let max=a.get("max_goal_rounds").map(positive).transpose()?.unwrap_or(256);if self.goal.as_ref().is_some_and(|g|g["phase"]!="complete"){return Err("GOAL_ALREADY_EXISTS".into())}self.goal=Some(json!({"id":format!("goal-{}",uuid::Uuid::new_v4()),"revision":1,"objective":obj,"phase":"active","roundsStarted":0,"maxGoalRounds":max}));self.armed=true;return Ok(self.view())}
 let id=a["goal_id"].as_str().filter(|s|!s.is_empty()&&*s==s.trim()).ok_or("goal_id must be non-empty")?;let rev=positive(&a["revision"])?;let action=a["action"].as_str().ok_or("action required")?;let current=self.goal.as_ref().ok_or("GOAL_NOT_FOUND")?;if current["id"]!=id||current["revision"]!=rev{return Err("GOAL_STALE_REVISION".into())}let round=matches!(&authority,Authority::GoalRound{id,revision,round} if current["id"]==id.as_str()&&current["revision"]==*revision&&current["roundsStarted"]==*round&&*round>0);
 if matches!(action,"edit"|"pause"|"resume"){if !human{return Err("this goal operation requires a direct human turn on a top-level agent".into())}}else if !human&&!round{return Err("complete and blocked require a direct human turn or the current goal round".into())}
 for k in ["objective","blocked_reason"]{if let Some(v)=a.get(k){if !v.is_string(){return Err(format!("{k} must be string"))}}}if let Some(v)=a.get("max_goal_rounds"){if !v.is_number(){return Err("max_goal_rounds must be number".into())}}
 let text=|k:&str|a[k].as_str().is_some_and(|s|!s.is_empty());let cap=a.get("max_goal_rounds").is_some_and(|v|v.as_f64()!=Some(0.0));let phase=current["phase"].as_str().unwrap_or("");let mut next=current.clone();let mut armed=self.armed;
 if action!="edit"&&(text("objective")||cap){return Err("objective and max_goal_rounds are valid only with action edit".into())}if action!="blocked"&&text("blocked_reason"){return Err("blocked_reason is valid only with action blocked".into())}
 match action{
 "edit"=>{if !text("objective")&&!cap{return Err("goal edit requires objective and/or maxGoalRounds".into())}if text("objective"){next["objective"]=json!(objective(&a["objective"])?)}if cap{next["maxGoalRounds"]=json!(positive(&a["max_goal_rounds"])?)}},
 "pause"=>{if phase!="active"{return Err("GOAL_INVALID_TRANSITION".into())}next["phase"]=json!("paused");armed=false;},
 "resume"=>{if phase=="paused"{return Err("the model cannot resume a paused goal; the user must resume it".into())}if !matches!(phase,"active"|"blocked")||(phase=="active"&&self.armed)||current["roundsStarted"].as_u64().unwrap()>=current["maxGoalRounds"].as_u64().unwrap(){return Err("GOAL_INVALID_TRANSITION".into())}next["phase"]=json!("active");next.as_object_mut().unwrap().remove("blockedReason");armed=true;},
 "complete"=>{if phase=="complete"{return Err("GOAL_INVALID_TRANSITION".into())}next["phase"]=json!("complete");next.as_object_mut().unwrap().remove("blockedReason");armed=false;},
 "blocked"=>{if phase!="active"{return Err("GOAL_INVALID_TRANSITION".into())}let reason=a["blocked_reason"].as_str().filter(|s|!s.trim().is_empty()).ok_or("blocked_reason is required with action blocked")?;if round&&!human&&current["roundsStarted"].as_u64().unwrap()<3{return Err("GOAL_TOOL_BLOCK_THRESHOLD".into())}next["phase"]=json!("blocked");next["blockedReason"]=json!({"code":"model-reported","message":reason});armed=false;},_=>return Err("invalid goal action".into())}
 next["revision"]=json!(rev.checked_add(1).filter(|n|*n<=9007199254740991).ok_or("goal revision overflow")?);self.goal=Some(next);self.armed=armed;Ok(self.view())
 }
 pub fn admit_round(&mut self)->Result<Option<Value>,String>{let Some(g)=self.goal.as_mut()else{return Ok(None)};if !self.armed||g["phase"]!="active"{return Ok(None)}let n=g["roundsStarted"].as_u64().ok_or("invalid rounds")?;let max=g["maxGoalRounds"].as_u64().ok_or("invalid cap")?;if n>=max{g["revision"]=json!(g["revision"].as_u64().unwrap()+1);g["phase"]=json!("blocked");g["blockedReason"]=json!({"code":"round-limit","message":format!("Goal reached its configured limit of {max} rounds.")});self.armed=false;return Ok(None)}g["roundsStarted"]=json!(n+1);Ok(Some(json!({"goalId":g["id"],"revision":g["revision"],"round":n+1,"objective":g["objective"],"maxGoalRounds":max})))}
}

pub fn card_text(value:&Value)->String{let g=&value["goal"];if g.is_null(){return "Goal: none".into()}format!("Goal [{}; {}] {} (round {}/{}, revision {})",g["phase"].as_str().unwrap_or("unknown"),value["activation"].as_str().unwrap_or("disarmed"),g["objective"].as_str().unwrap_or(""),g["roundsStarted"],g["maxGoalRounds"],g["revision"])}

pub fn round_prompt(source:&Value)->String{format!("<goal_round>\nObjective: {}\nRound: {}/{}\n\nContinue working toward the objective in this same session. Treat the current workspace, tool results, and durable session state as authoritative; inspect them instead of assuming earlier narration is still current. Make concrete progress and verify the result. Before claiming completion, gather evidence that the whole objective is achieved, read the current goal, and mark it complete. If work remains, leave the goal active for the next round. Follow the configured goal-tool policy before reporting a blocker.\n</goal_round>",source["objective"],source["round"],source["maxGoalRounds"])}
