//! Session-owned shell jobs. Foreground deadline promotes; it never kills.
use std::{path::{Path,PathBuf},collections::BTreeMap,sync::{Arc,Mutex},time::{Duration,Instant,SystemTime,UNIX_EPOCH},io::Read};
use serde_json::{json,Value};
struct State{stdout:Vec<u8>,stderr:Vec<u8>,out_base:usize,err_base:usize,out_path:PathBuf,err_path:PathBuf,code:Option<i32>,signal:Option<String>,io_errors:Vec<String>,process_exited:bool,cancelled:bool,cancel_reason:Option<String>,finished:Option<u64>}
struct Job{notified:bool,awaited:bool,collected:bool,id:String,label:String,pid:u32,started:u64,state:Arc<Mutex<State>>,out_cursor:usize,err_cursor:usize}
pub struct JobSession{session_id:String,root:PathBuf,jobs:BTreeMap<String,Job>}
fn now()->u64{SystemTime::now().duration_since(UNIX_EPOCH).unwrap_or_default().as_millis() as u64}
fn validate(a:&Value,allowed:&[&str])->Result<(),String>{let o=a.as_object().ok_or("arguments must be object")?;for k in o.keys(){if !allowed.contains(&k.as_str()){return Err(format!("unknown argument {k}"))}}Ok(())}
fn positive(a:&Value,k:&str,default:f64,cap:f64)->Result<Duration,String>{let n=a.get(k).map(|x|x.as_f64().ok_or_else(||format!("{k} must be positive number"))).transpose()?.unwrap_or(default);if !n.is_finite()||n<=0.0{return Err(format!("{k} must be positive number"))}Ok(Duration::from_secs_f64(n.min(cap)/1000.0))}
fn flag(a:&Value,k:&str)->Result<bool,String>{a.get(k).map(|v|v.as_bool().ok_or_else(||format!("{k} must be boolean"))).transpose().map(|v|v.unwrap_or(false))}
fn view(j:&Job)->Value{let s=j.state.lock().unwrap();let status=if s.finished.is_none(){if s.cancelled{"stopping"}else{"running"}}else if s.cancelled{"killed"}else if s.code==Some(0)&&s.io_errors.is_empty(){"completed"}else{"failed"};let mut v=json!({"id":j.id,"kind":"bash","label":j.label,"status":status,"startedAt":j.started});if let Some(t)=s.finished{v["finishedAt"]=json!(t)}if let Some(reason)=&s.cancel_reason{v["detail"]=json!(reason)}else if !s.io_errors.is_empty(){v["detail"]=json!(s.io_errors.join("; "))}else if let Some(sig)=&s.signal{v["detail"]=json!(format!("signal: {sig}"))}v}
const OUTPUT_CAP:usize=30000;
fn retain(buf:&mut Vec<u8>,base:&mut usize,bytes:&[u8]){buf.extend_from_slice(bytes);if buf.len()>OUTPUT_CAP{let mut n=buf.len()-OUTPUT_CAP;while n<buf.len() && buf[n]&0xc0==0x80{n+=1}buf.drain(..n);*base+=n}}
fn consume_stream(buf:&[u8],base:usize,cursor:&mut usize,finished:bool)->String{
 let start=cursor.saturating_sub(base).min(buf.len());let bytes=&buf[start..];
 let n=if finished{bytes.len()}else{match std::str::from_utf8(bytes){Ok(_)=>bytes.len(),Err(e) if e.error_len().is_none()=>e.valid_up_to(),Err(_)=>bytes.len()}};
 *cursor=base+start+n;String::from_utf8_lossy(&bytes[..n]).to_string()
}
fn delta(j:&mut Job)->String{let s=j.state.lock().unwrap();let lost=j.out_cursor<s.out_base||j.err_cursor<s.err_base;let done=s.finished.is_some();let out=consume_stream(&s.stdout,s.out_base,&mut j.out_cursor,done);let err=consume_stream(&s.stderr,s.err_base,&mut j.err_cursor,done);let mut text=if err.is_empty(){out}else{format!("{out}{}[stderr]\n{err}",if out.is_empty()||out.ends_with('\n'){""}else{"\n"})};if lost{text.push_str(&format!("\n[some output was dropped from memory; full output: {}, {}]",s.out_path.display(),s.err_path.display()))}text}

fn wait(j:&Job,d:Duration){let start=Instant::now();while j.state.lock().unwrap().finished.is_none()&&start.elapsed()<d{std::thread::sleep(Duration::from_millis(5))}}
impl JobSession{
 pub fn retry_notice(&mut self,id:&str){if let Some(job)=self.jobs.get_mut(id){job.notified=false}}
 pub fn owned_pids(&self)->Vec<u32>{self.jobs.values().map(|j|j.pid).collect()}
 pub fn uncollected(&self)->Vec<String>{self.jobs.values().filter(|j|!j.collected&&!j.state.lock().unwrap().cancelled).map(|j|j.id.clone()).collect()}
 pub fn notifications(&mut self)->Vec<Value>{let mut out=vec![];for j in self.jobs.values_mut(){let settled={let s=j.state.lock().unwrap();s.finished.is_some()&&!s.cancelled};if settled&&!j.notified&&!j.awaited{j.notified=true;out.push(json!({"job":view(j),"text":format!("Background job {} finished; collect its newer output with job_output.",j.id)}));}}out}
 pub fn new(root:&Path)->Self{Self{session_id:uuid::Uuid::new_v4().to_string(),root:root.to_path_buf(),jobs:BTreeMap::new()}}
 pub fn bash(&mut self,a:&Value)->Result<Value,String>{
  validate(a,&["description","command","timeoutMs","workdir","run_in_background","sandbox_permissions","justification"])?;
  let command=a["command"].as_str().filter(|s|!s.trim().is_empty()).ok_or("command must be non-empty string")?;
  a["description"].as_str().filter(|s|!s.trim().is_empty()).ok_or("description must be non-empty string")?;
  if let Some(mode)=a.get("sandbox_permissions"){let mode=mode.as_str().ok_or("sandbox_permissions must be string")?;if !matches!(mode,"workspace-write"|"danger-full-access"){return Err("invalid sandbox_permissions".into())}if mode!="workspace-write"{let reason=a["justification"].as_str().filter(|s|!s.trim().is_empty()).ok_or("invalid escalation: sandbox_permissions requires a justification")?;let _=reason;return Err("sandbox escalation requires separate approval; not executed".into())}}else if a.get("justification").is_some(){return Err("invalid escalation: justification is only valid together with sandbox_permissions".into())}
  let timeout=positive(a,"timeoutMs",120000.0,600000.0)?;let background=flag(a,"run_in_background")?;
  let root=self.root.canonicalize().map_err(|e|e.to_string())?;let wd=match a.get("workdir"){None=>root.clone(),Some(v)=>{let p=v.as_str().ok_or("workdir must be string")?;if Path::new(p).is_absolute(){PathBuf::from(p)}else{root.join(p)}}};
  let mut spill=root.clone();for component in [".hs","jobs"]{spill.push(component);match std::fs::symlink_metadata(&spill){Ok(m) if m.file_type().is_symlink()||!m.is_dir()=>return Err("spill path must be a real directory inside root".into()),Ok(_)=>{},Err(e) if e.kind()==std::io::ErrorKind::NotFound=>std::fs::create_dir(&spill).map_err(|e|e.to_string())?,Err(e)=>return Err(e.to_string())}if !spill.canonicalize().map_err(|e|e.to_string())?.starts_with(&root){return Err("spill path escapes root".into())}}let spill_id=uuid::Uuid::new_v4();let out_path=spill.join(format!("{spill_id}.stdout"));let err_path=spill.join(format!("{spill_id}.stderr"));let out_file=std::fs::OpenOptions::new().write(true).create_new(true).open(&out_path).map_err(|e|e.to_string())?;let err_file=std::fs::OpenOptions::new().write(true).create_new(true).open(&err_path).map_err(|e|e.to_string())?;
  let quoted_home=format!("'{}'",root.join(".hs").display().to_string().replace('\'',"'\"'\"'"));let wrapped=format!("export DSH_SHELL=1 DSH_SESSION_ID='{}' DSH_HOME={quoted_home};\n{command}",self.session_id);
  let mut child=crate::termexec::spawn_managed_status(&root,&wd,&wrapped).map_err(|v|v.to_string())?;let pid=child.id();let out=child.stdout.take().ok_or("stdout unavailable")?;let err=child.stderr.take().ok_or("stderr unavailable")?;
  let state=Arc::new(Mutex::new(State{stdout:vec![],stderr:vec![],out_base:0,err_base:0,out_path,err_path,code:None,signal:None,io_errors:vec![],process_exited:false,cancelled:false,cancel_reason:None,finished:None}));let so=state.clone();
  let output=std::thread::spawn(move||drain_frames(out,out_file,err_file,&so));
  let errors=std::thread::spawn(move||{let mut text=String::new();match err.take(65536).read_to_string(&mut text){Ok(_)=>if text.is_empty(){vec![]}else{vec![format!("sandbox supervisor: {text}")]},Err(e)=>vec![format!("supervisor stderr read failed: {e}")]}});
  let done=state.clone();std::thread::spawn(move||{let status=child.wait();done.lock().unwrap().process_exited=true;let mut io_errors=vec![];for thread in [output,errors]{match thread.join(){Ok(e)=>io_errors.extend(e),Err(_)=>io_errors.push("output worker panicked".into())}}let mut s=done.lock().unwrap();if let Err(e)=status{io_errors.push(format!("process wait failed: {e}"))}if s.cancelled{io_errors.clear()}s.io_errors=io_errors;s.finished=Some(now());});
  let id=uuid::Uuid::new_v4().to_string();let mut j=Job{notified:false,awaited:false,collected:false,id:id.clone(),label:command.into(),pid,started:now(),state,out_cursor:0,err_cursor:0};
  if background{self.jobs.insert(id.clone(),j);return Ok(json!({"kind":"background","jobId":id}))}
  wait(&j,timeout);
  if j.state.lock().unwrap().finished.is_none(){let text=delta(&mut j);self.jobs.insert(id.clone(),j);return Ok(json!({"kind":"promoted","jobId":id,"timeoutMs":timeout.as_millis(),"output":text}))}
  let s=j.state.lock().unwrap();if !s.io_errors.is_empty(){return Err(format!("command completed but output capture failed: {}",s.io_errors.join("; ")))}Ok(json!({"kind":"foreground","timeoutMs":timeout.as_millis(),"exitCode":s.code,"signal":s.signal,"timedOut":false,"aborted":false,"stdout":{"text":String::from_utf8_lossy(&s.stdout),"truncated":s.out_base>0,"spillPath":s.out_path},"stderr":{"text":String::from_utf8_lossy(&s.stderr),"truncated":s.err_base>0,"spillPath":s.err_path}}))
 }
 pub fn output(&mut self,a:&Value)->Result<Value,String>{validate(a,&["job_id","wait","timeout_ms"])?;let id=a["job_id"].as_str().ok_or("job_id required")?;let should_wait=flag(a,"wait")?;let d=positive(a,"timeout_ms",30000.0,600000.0)?;let j=self.jobs.get_mut(id).ok_or("unknown job for this session")?;if should_wait{wait(j,d);if j.state.lock().unwrap().finished.is_some(){j.awaited=true}}let text=delta(j);if j.state.lock().unwrap().finished.is_some(){j.collected=true;}Ok(json!({"text":text,"job":view(j)}))}
 pub fn list(&mut self,a:&Value)->Result<Value,String>{validate(a,&[])?;Ok(Value::Array(self.jobs.values().map(view).collect()))}
 pub fn kill(&mut self,a:&Value)->Result<Value,String>{validate(a,&["job_id","reason"])?;let id=a["job_id"].as_str().ok_or("job_id required")?;if let Some(v)=a.get("reason"){if !v.is_string(){return Err("reason must be string".into())}}let j=self.jobs.get(id).ok_or("unknown job for this session")?;let mut s=j.state.lock().unwrap();let outcome=if s.finished.is_some(){"already-finished"}else{let ok=std::process::Command::new("kill").args(["-TERM","--",&format!("-{}",j.pid)]).status().map_err(|e|e.to_string())?;if !ok.success(){return Err("cancellation signal failed".into())}s.cancelled=true;s.cancel_reason=a["reason"].as_str().map(str::to_owned);let state=j.state.clone();let pid=j.pid;std::thread::spawn(move||{std::thread::sleep(Duration::from_millis(250));let s=state.lock().unwrap();if s.finished.is_none(){let _=std::process::Command::new("kill").args(["-KILL","--",&format!("-{pid}")]).status();}});"cancellation-requested"};drop(s);Ok(json!({"outcome":outcome,"job":view(j)}))}
}

impl Drop for JobSession{fn drop(&mut self){for j in self.jobs.values(){let s=j.state.lock().unwrap();if s.finished.is_none(){let _=std::process::Command::new("kill").args(["-KILL","--",&format!("-{}",j.pid)]).status();}}for j in self.jobs.values(){while j.state.lock().unwrap().finished.is_none(){std::thread::sleep(Duration::from_millis(5));}}}}
fn signal_name(n:i32)->String{match n{1=>"SIGHUP".into(),2=>"SIGINT".into(),9=>"SIGKILL".into(),13=>"SIGPIPE".into(),15=>"SIGTERM".into(),_=>format!("SIG{n}")}}
fn drain_frames(out:impl Read,mut out_file:impl std::io::Write,mut err_file:impl std::io::Write,so:&Arc<Mutex<State>>)->Vec<String>{
use std::io::{BufRead,BufReader,Write};let mut io_errors=vec![];let mut settled=false;for line in BufReader::new(out).lines(){let line=match line{Ok(v)=>v,Err(e)=>{io_errors.push(format!("frame read failed: {e}"));break}};let v=match serde_json::from_str::<Value>(&line){Ok(v)=>v,Err(e)=>{io_errors.push(format!("invalid supervisor frame: {e}"));continue}};if v["settled"]==true{settled=true;let mut s=so.lock().unwrap();s.code=v["exit_code"].as_i64().map(|n|n as i32);s.signal=v["signal"].as_i64().map(|n|signal_name(n as i32));continue}if let Some(e)=v["error"].as_str(){io_errors.push(e.into());continue}let Some(bytes)=v["bytes"].as_array().and_then(|a|a.iter().map(|n|n.as_u64().and_then(|n|u8::try_from(n).ok())).collect::<Option<Vec<_>>>())else{io_errors.push("invalid supervisor bytes".into());continue};let is_err=v["channel"]=="stderr";let file:&mut dyn Write=if is_err{&mut err_file}else{&mut out_file};if let Err(e)=file.write_all(&bytes){if io_errors.len()<8{io_errors.push(format!("spill write failed: {e}"))}}let mut s=so.lock().unwrap();if is_err{let State{stderr,err_base,..}=&mut *s;retain(stderr,err_base,&bytes)}else{let State{stdout,out_base,..}=&mut *s;retain(stdout,out_base,&bytes)}}if !settled{io_errors.push("supervisor ended without payload status".into())}for f in [&mut out_file as &mut dyn Write,&mut err_file as &mut dyn Write]{if let Err(e)=f.flush(){io_errors.push(format!("spill flush failed: {e}"))}}io_errors}pub fn render(tool:&str,v:&Value)->String{
 if let Some(e)=v.get("error"){return format!("Error: {e}")}
 let status=|j:&Value|{let detail=j["detail"].as_str().map(|d|format!(", {d}")).unwrap_or_default();format!("[status: {}{detail}]",j["status"].as_str().unwrap_or("unknown"))};
 match tool{
 "job_output"=>{let text=v["text"].as_str().unwrap_or("");format!("{}\n{}",if text.is_empty(){"(no new output)"}else{text.trim_end_matches('\n')},status(&v["job"]))},
 "job_kill"=>if v["outcome"]=="already-finished"{format!("job {} had already finished {}",v["job"]["id"].as_str().unwrap_or(""),status(&v["job"]))}else{format!("requested cancellation of job {}",v["job"]["id"].as_str().unwrap_or(""))},
 "job_list"=>{let jobs=v.as_array().cloned().unwrap_or_default();if jobs.is_empty(){"(no background jobs)".into()}else{jobs.iter().map(|j|format!("{} [{}] {} - {}",j["id"].as_str().unwrap_or(""),j["kind"].as_str().unwrap_or(""),j["status"].as_str().unwrap_or(""),j["label"].as_str().unwrap_or(""))).collect::<Vec<_>>().join("\n")}},
 "bash"=>match v["kind"].as_str(){
 Some("background")=>format!("started background job {}",v["jobId"].as_str().unwrap_or("")),
 Some("promoted")=>{let out=v["output"].as_str().unwrap_or("");format!("{}{}[still running after {}ms; moved to background job {}]\nThe command keeps running in the background. You will be notified when it finishes; read newer output with job_output, stop it with job_kill.",out,if out.is_empty()||out.ends_with('\n'){""}else{"\n"},v["timeoutMs"],v["jobId"].as_str().unwrap_or(""))},
 Some("foreground")=>{let stream=|s:&Value|{let text=s["text"].as_str().unwrap_or("");if s["truncated"]==true{format!("{text}\n[output truncated; full output: {}]",s["spillPath"].as_str().unwrap_or("(unavailable)"))}else{text.into()}};let mut body=stream(&v["stdout"]);let err=stream(&v["stderr"]);if !err.is_empty(){if !body.is_empty()&&!body.ends_with('\n'){body.push('\n')}body.push_str(&format!("[stderr]\n{err}"))}if body.is_empty(){body="(no output)".into()}let marker=if let Some(sig)=v["signal"].as_str(){Some(format!("[killed by signal: {sig}]"))}else if v["exitCode"]!=0{Some(format!("[exit code: {}]",v["exitCode"]))}else{None};if let Some(m)=marker{if !body.ends_with('\n'){body.push('\n')}body.push_str(&m)}body},
 _=>v.to_string()},_=>v.to_string()}
}

#[cfg(test)]mod io_tests{use super::*;struct Broken;impl std::io::Write for Broken{fn write(&mut self,_:&[u8])->std::io::Result<usize>{Err(std::io::Error::other("spill unavailable"))}fn flush(&mut self)->std::io::Result<()>{Ok(())}}fn state()->Arc<Mutex<State>>{Arc::new(Mutex::new(State{stdout:vec![],stderr:vec![],out_base:0,err_base:0,out_path:PathBuf::new(),err_path:PathBuf::new(),code:None,signal:None,io_errors:vec![],process_exited:false,cancelled:false,cancel_reason:None,finished:None}))}#[test]fn framed_production_drain_reports_spill_failure(){let s=state();let frames=b"{\"channel\":\"stdout\",\"bytes\":[104,105]}\n{\"settled\":true,\"exit_code\":0,\"signal\":null}\n";let e=drain_frames(std::io::Cursor::new(frames),Broken,vec![],&s);assert_eq!(s.lock().unwrap().stdout,b"hi");assert!(e.iter().any(|e|e.contains("spill unavailable")));}#[test]fn missing_payload_status_cannot_be_success(){let s=state();let e=drain_frames(std::io::Cursor::new(b""),vec![],vec![],&s);assert!(e.iter().any(|e|e.contains("without payload status")));}}
