//! Session planning collaboration state. Independent of legacy enforced plan gate.
use serde_json::{json,Value};
#[derive(Clone,Default)]pub struct PlanSession{pub active:bool,pub pending:Option<bool>,pub section:String}
impl PlanSession{
 pub fn select(&mut self,active:bool,open:bool)->&'static str{if self.pending.unwrap_or(self.active)==active{return "noop"}if open{self.pending=Some(active);return if self.active==active{"cancelled"}else{"queued"}}self.pending=None;if self.active==active{"cancelled"}else{self.active=active;"committed"}}
 pub fn boundary(&mut self)->Option<bool>{let target=self.pending.take()?;if target==self.active{return None}self.active=target;Some(target)}
 pub fn review(&mut self,args:&Value,answer:Option<&Value>)->Result<Value,String>{if !self.active{return Err("exit_plan_mode is only available in plan mode".into())}let plan=args["plan"].as_str().ok_or("plan must be string")?;let t=plan.trim();let rest=t.strip_prefix('#').ok_or("exit_plan_mode requires a non-empty markdown plan starting with a # heading")?;if !rest.chars().next().is_some_and(char::is_whitespace)||rest.trim().is_empty(){return Err("exit_plan_mode requires a non-empty markdown plan starting with a # heading".into())}let answer=answer.ok_or("no user-questions channel is available to review the plan; ask the user to switch the session mode instead")?;let items:Vec<_>=answer["answers"].as_array().into_iter().flatten().filter(|a|a["id"]=="plan-review").collect();let item=if items.len()==1{Some(items[0])}else{None};let approved=item.is_some_and(|a|a["selected"]==json!(["Approve"])&&a.get("custom").is_none());if !approved{let feedback=item.and_then(|a|a["custom"].as_str()).unwrap_or("");return Err(if feedback.is_empty(){"The user chose to keep planning; revise the plan and present it again.".into()}else{format!("The user chose to keep planning; their feedback: {feedback}")})}self.pending=Some(false);Ok(json!({"approved":true}))}
}

pub fn question(plan:&str,call_id:uuid::Uuid)->Value{json!({"questions":[{"id":"plan-review","header":"Plan review","question":"Approve this plan and leave plan mode?","detail":plan,"options":[{"label":"Approve","description":"Leave plan mode; the plan is carried out from the next step."},{"label":"Keep planning","description":"Stay in plan mode; feedback goes back to the model."}],"intent":{"kind":"plan-review","approve":"Approve","callId":call_id}}]})}
pub fn render()->&'static str{"Plan approved \u{2014} plan mode exited; carry out the plan starting with your next step."}
