//! Native dsh filesystem skill discovery. Roots are session-owned, never process overrides.
use std::path::{Path,PathBuf};use serde_json::{json,Value};
#[derive(Clone)]pub struct SkillRoot{pub path:PathBuf,pub rank:u32,pub skip_system:bool}
#[derive(Clone)]struct Entry{name:String,description:String,content:String,base:PathBuf,model:bool,user:bool,definition:Option<Value>,rank:f64,lazy:Option<(std::sync::Arc<dyn SkillProvider>,Candidate)>}
pub fn valid_name(s:&str)->bool{!s.is_empty()&&s.split('-').all(|p|!p.is_empty()&&p.bytes().all(|c|c.is_ascii_lowercase()||c.is_ascii_digit()))}
fn boolean(v:Option<&Value>)->Result<Option<bool>,String>{match v{None=>Ok(None),Some(Value::Bool(b))=>Ok(Some(*b)),Some(v)=>{let s=v.as_str().map(str::to_lowercase).unwrap_or_else(||v.to_string());match s.as_str(){"1"|"true"|"yes"|"on"=>Ok(Some(true)),"0"|"false"|"no"|"off"=>Ok(Some(false)),_=>Err("invalid invocation boolean".into())}}}}
fn parse(path:&Path,base:&Path)->Option<Entry>{let raw=std::fs::read_to_string(path).ok()?;let mut lines=raw.split_inclusive('\n');if lines.next()?.trim_end_matches(['\r','\n'])!="---"{return None}let mut yaml=String::new();let mut offset=raw.find('\n')?+1;let mut closed=false;for line in lines{offset+=line.len();if line.trim_end_matches(['\r','\n'])=="---"{closed=true;break}yaml.push_str(line);}if !closed{return None}let meta:Value=serde_yaml_ng::from_str(&yaml).ok()?;let name=meta["name"].as_str()?.to_owned();let description=meta["description"].as_str()?.to_owned();if !valid_name(&name)||description.is_empty(){return None}if ["disableModelInvocation","modelInvocable","userInvocable"].iter().any(|k|meta.get(k).is_some()){return None}let model=boolean(meta.get("disable-model-invocation")).ok()?!=Some(true);let user=boolean(meta.get("user-invocable")).ok()?!=Some(false);Some(Entry{name,description,content:raw[offset..].trim().to_owned(),base:base.to_owned(),model,user,definition:None,rank:0.0,lazy:None})}
fn discover(roots:&[SkillRoot])->Result<Vec<Entry>,String>{let mut roots=roots.to_vec();roots.sort_by_key(|r|r.rank);let mut entries=std::collections::BTreeMap::new();for root in roots{let children=match std::fs::read_dir(&root.path){Ok(v)=>v,Err(e) if e.kind()==std::io::ErrorKind::NotFound=>continue,Err(e)=>return Err(format!("skill discovery {}: {e}",root.path.display()))};let mut children:Vec<_>=children.collect::<Result<_,_>>().map_err(|e|e.to_string())?;children.sort_by_key(|e|e.file_name());for child in children{if root.skip_system&&child.file_name()==".system"{continue}let p=child.path();let (file,base)=if p.is_dir(){(p.join("SKILL.md"),p)}else if p.extension().is_some_and(|s|s=="md"){(p,root.path.clone())}else{continue};if let Some(mut e)=parse(&file,&base){e.rank=f64::from(root.rank);entries.entry(e.name.clone()).or_insert(e);}}}Ok(entries.into_values().collect())}
pub fn call(roots:&[SkillRoot],args:&Value)->Result<Value,String>{let o=args.as_object().ok_or("arguments must be object")?;if o.len()!=1||!o.contains_key("name"){return Err("skill requires only name".into())}let name=args["name"].as_str().ok_or("name must be string")?;if !valid_name(name){return Err(format!("invalid skill name \"{name}\""))}let e=discover(roots)?.into_iter().find(|e|e.name==name).ok_or_else(||format!("skill \"{name}\" is unknown or no longer available"))?;if !e.model{return Err(format!("skill \"{name}\" is not available for model invocation"))}if let Some((p,c))=&e.lazy{let skill=p.get(c)?.ok_or_else(||format!("skill \"{}\" is unknown or no longer available",e.name))?;if skill.name!=e.name{return Err(format!("skill \"{}\" is unknown or no longer available",e.name))}if !skill.invocation.model_invocable{return Err(format!("skill \"{}\" is not available for model invocation",e.name))}if !valid_name(&skill.name)||skill.description.is_empty(){return Err("invalid loaded skill definition".into())}Ok(value(&entry_runtime(&skill)))}else{Ok(value(&e))} }
fn escaped(s:&str)->String{s.replace('&',"&amp;").replace('<',"&lt;").replace('>',"&gt;")}
pub fn render(v:&Value)->String{let base=&v["resourceBase"];let hint=match base["kind"].as_str(){Some("directory")=>format!("Base directory for this skill: {}\nResolve relative paths mentioned by this skill against the base directory before using them. Load referenced resources only as needed.",escaped(base["path"].as_str().unwrap_or(""))),Some("url")=>format!("Base URL for this skill: {}\nResolve relative URLs mentioned by this skill against the base URL before using them. Load referenced resources only as needed.",escaped(base["url"].as_str().unwrap_or(""))),Some("opaque")=>format!("Resources for this skill: {}\nLoad referenced resources only as needed.",escaped(base["description"].as_str().unwrap_or(""))),_=>format!("Resources for this skill are managed by provider \"{}\".\nLoad referenced resources only as needed.",escaped(v["provider"].as_str().unwrap_or("")))};format!("<skill_content name=\"{}\">\n<skill_resources>\n{}\n</skill_resources>\n\n<skill_instructions>\n{}\n</skill_instructions>\n</skill_content>",v["name"].as_str().unwrap_or("").replace('&',"&amp;").replace('\"',"&quot;").replace('<',"&lt;"),hint,v["content"].as_str().unwrap_or(""))}

pub fn catalog(roots:&[SkillRoot])->Result<Value,String>{Ok(Value::Array(discover(roots)?.into_iter().filter(|e|e.model).map(|e|json!({"name":e.name,"description":({let normalized=e.description.split_whitespace().collect::<Vec<_>>().join(" ");if normalized.encode_utf16().count()>500{format!("{}...",normalized.chars().scan(0,|units,c|{*units+=c.len_utf16();(*units<=497).then_some(c)}).collect::<String>())}else{normalized}})})).collect()))}
pub fn project_roots(cwd:&Path)->Vec<SkillRoot>{let root=cwd.ancestors().find(|p|p.join(".git").exists()).unwrap_or(cwd);vec![SkillRoot{path:root.join(".dsh/skills"),rank:100,skip_system:false},SkillRoot{path:root.join(".agents/skills"),rank:200,skip_system:false}]}
pub fn catalog_text(entries:&Value,update:bool)->String{let lines=entries.as_array().into_iter().flatten().map(|e|format!("- `{}`: {}",e["name"].as_str().unwrap_or(""),escaped(e["description"].as_str().unwrap_or("")))).collect::<Vec<_>>().join("\n");if update{let availability=if entries.as_array().is_some_and(Vec::is_empty){"No skills are currently available through the `skill` tool. Do not use names from earlier skill catalogs.\nA user may still invoke a skill directly; its <skill_content> block then appears in this conversation. Follow it, and do not call the `skill` tool for it."}else{"Use only names in this replacement catalog. If the user names a listed skill, or the task clearly matches its description, call the `skill` tool with the exact name before acting.\nA user may also invoke a skill directly; its <skill_content> block then appears in this conversation. Follow it, and do not call the `skill` tool again for that skill."};format!("<system-reminder>\nThe available skill catalog changed. This complete catalog replaces every earlier available-skills list in this session:\n\n<available_skills>\n{lines}\n</available_skills>\n\n{availability}\n</system-reminder>")}else{format!("<system-reminder>\nA skill is a reusable set of task-specific instructions. The following skills are available in this session:\n\n<available_skills>\n{lines}\n</available_skills>\n\nIf the user names a skill, or the task clearly matches a skill's description, call the `skill` tool with the exact skill name before taking task actions. Load all applicable skills, then follow their full instructions. This catalog contains summaries only; do not infer or follow a skill's instructions until it has been loaded.\nA user may also invoke a skill directly; its <skill_content> block then appears in this conversation. Follow it, and do not call the `skill` tool again for that skill.\n</system-reminder>")}}
#[derive(Clone,serde::Deserialize)]#[serde(default,deny_unknown_fields,rename_all="camelCase")]pub struct RootConfig{pub include_default_roots:bool,pub dsh_home:Option<PathBuf>,pub agents_home:Option<PathBuf>,pub custom_skill_dirs:Vec<PathBuf>,pub bundled_skill_dir:Option<PathBuf>}
impl Default for RootConfig{fn default()->Self{Self{include_default_roots:true,dsh_home:None,agents_home:None,custom_skill_dirs:vec![],bundled_skill_dir:None}}}
impl RootConfig{pub fn roots(&self,project:Option<&Path>)->Vec<SkillRoot>{let home=std::env::var_os("HOME").map(PathBuf::from);let mut roots=if self.include_default_roots{project.map(project_roots).unwrap_or_default()}else{vec![]};roots.extend(self.custom_skill_dirs.iter().map(|p|SkillRoot{path:p.clone(),rank:300,skip_system:false}));if self.include_default_roots{if let Some(p)=self.dsh_home.clone().or_else(||home.as_ref().map(|h|h.join(".dsh"))){roots.push(SkillRoot{path:p.join("skills"),rank:400,skip_system:true});}if let Some(p)=self.agents_home.clone().or_else(||home.as_ref().map(|h|h.join(".agents"))){roots.push(SkillRoot{path:p.join("skills"),rank:500,skip_system:false});}}if let Some(p)=self.bundled_skill_dir.clone(){roots.push(SkillRoot{path:p,rank:600,skip_system:false});}roots}}

/// Scan only host-attested direct user text. Gesture boundaries are whitespace,
/// not punctuation or path separators, and first-seen order is preserved.
pub fn gestures(text:&str)->Vec<String>{let mut names=vec![];for token in text.split_whitespace(){if let Some(name)=token.strip_prefix('/') {if valid_name(name)&&!names.iter().any(|s|s==name){names.push(name.to_owned());}}}names}
pub fn direct(roots:&[SkillRoot],text:&str)->Result<Vec<Value>,String>{let names=gestures(text);if names.is_empty(){return Ok(vec![])}let entries=discover(roots)?;Ok(names.iter().filter_map(|name|entries.iter().find(|e|&e.name==name&&e.user)).map(load_user).collect::<Result<Vec<_>,_>>()?.into_iter().flatten().collect())}

pub fn user_names(roots:&[SkillRoot])->Result<Vec<String>,String>{Ok(discover(roots)?.into_iter().filter(|e|e.user).map(|e|e.name).collect())}
pub fn starts_user_gesture(text:&str,names:&[String])->bool{text.trim().split_whitespace().next().and_then(|t|t.strip_prefix('/')).is_some_and(|name|valid_name(name)&&names.iter().any(|n|n==name))}

#[derive(Clone,serde::Deserialize,serde::Serialize)]#[serde(rename_all="camelCase")]pub struct RuntimeSkill{pub name:String,pub description:String,pub content:String,pub source:String,#[serde(default="runtime_provider")]pub provider:String,#[serde(default)]pub invocation:Invocation,#[serde(default,skip_serializing_if="Option::is_none")]pub resource_base:Option<Value>}
fn runtime_provider()->String{"runtime".into()}
#[derive(Clone,serde::Deserialize,serde::Serialize)]#[serde(rename_all="camelCase")]pub struct Invocation{pub model_invocable:bool,pub user_invocable:bool}
impl Default for Invocation{fn default()->Self{Self{model_invocable:true,user_invocable:true}}}

fn value(e:&Entry)->Value{e.definition.clone().unwrap_or_else(||json!({"name":e.name,"provider":"filesystem","resourceBase":{"kind":"directory","path":e.base},"content":e.content}))}
#[derive(Default)]pub struct Registry{runtime:std::collections::BTreeMap<String,RuntimeSkill>,scopes:std::collections::BTreeMap<String,Registry>,providers:Vec<std::sync::Arc<dyn SkillProvider>>,incomplete:std::cell::Cell<bool>}
impl Registry{
 pub fn snapshot_scoped(&self,roots:&[SkillRoot],chain:&[String])->Result<(Value,bool),String>{self.incomplete.set(false);for scope in chain{if let Some(layer)=self.scopes.get(scope){layer.incomplete.set(false);}}let entries=self.catalog_scoped(roots,chain)?;let complete=!self.incomplete.get()&&!chain.iter().any(|scope|self.scopes.get(scope).is_some_and(|layer|layer.incomplete.get()));Ok((entries,complete))}
 pub fn register_provider(&mut self,scope:Option<&str>,provider:std::sync::Arc<dyn SkillProvider>)->Result<(),String>{if let Some(scope)=scope{if scope.is_empty(){return Err("scope must be non-empty".into())}return self.scopes.entry(scope.to_owned()).or_default().register_provider(None,provider)}if provider.name()=="runtime"||self.providers.iter().any(|p|p.name()==provider.name()){return Err("skill provider name reserved or already registered".into())}self.providers.push(provider);Ok(())}
 pub fn remove_provider(&mut self,scope:Option<&str>,name:&str)->bool{if let Some(scope)=scope{return self.scopes.get_mut(scope).is_some_and(|s|s.remove_provider(None,name))}let len=self.providers.len();self.providers.retain(|p|p.name()!=name);len!=self.providers.len()}
 pub fn register_scoped(&mut self,scope:&str,skill:RuntimeSkill)->Result<bool,String>{if scope.is_empty(){return Err("scope must be non-empty".into())}self.scopes.entry(scope.to_owned()).or_default().register(skill)}
 pub fn remove_scope(&mut self,scope:&str)->bool{self.scopes.remove(scope).is_some()}
 pub fn call_scoped(&self,roots:&[SkillRoot],chain:&[String],args:&Value)->Result<Value,String>{Self::call_entries(self.scoped_merged(roots,chain)?,args)}

 fn scoped_merged(&self,roots:&[SkillRoot],chain:&[String])->Result<Vec<Entry>,String>{let mut merged=std::collections::BTreeMap::new();for e in self.merged(roots)?{merged.insert(e.name.clone(),e);}for scope in chain{if let Some(layer)=self.scopes.get(scope){for e in layer.merged(&[])?{merged.insert(e.name.clone(),e);}}}Ok(merged.into_values().collect())}
 pub fn catalog_scoped(&self,roots:&[SkillRoot],chain:&[String])->Result<Value,String>{Ok(Value::Array(self.scoped_merged(roots,chain)?.into_iter().filter(|e|e.model).map(|e|json!({"name":e.name,"description":catalog_description(&e.description)})).collect()))}
 pub fn user_names_scoped(&self,roots:&[SkillRoot],chain:&[String])->Result<Vec<String>,String>{Ok(self.scoped_merged(roots,chain)?.into_iter().filter(|e|e.user).map(|e|e.name).collect())}
 pub fn direct_scoped(&self,roots:&[SkillRoot],chain:&[String],text:&str)->Result<Vec<Value>,String>{let names=gestures(text);if names.is_empty(){return Ok(vec![])}let entries=self.scoped_merged(roots,chain)?;Ok(names.iter().filter_map(|name|entries.iter().find(|e|&e.name==name&&e.user)).map(load_user).collect::<Result<Vec<_>,_>>()?.into_iter().flatten().collect())}
 pub fn register(&mut self,skill:RuntimeSkill)->Result<bool,String>{if !valid_name(&skill.name)||skill.description.is_empty(){return Err("invalid runtime skill name or description".into())}if self.runtime.contains_key(&skill.name){return Ok(false)}self.runtime.insert(skill.name.clone(),skill);Ok(true)}
 pub fn remove(&mut self,name:&str)->bool{self.runtime.remove(name).is_some()}
 fn merged(&self,roots:&[SkillRoot])->Result<Vec<Entry>,String>{let mut candidates=discover(roots)?;for skill in self.runtime.values(){candidates.push(entry_runtime(skill));}for provider in &self.providers{let Ok(obs)=provider.list()else{self.incomplete.set(true);continue};if !obs.complete{self.incomplete.set(true);}for c in obs.candidates{validate_candidate(&c,provider.name())?;candidates.push(Entry{name:c.name.clone(),description:c.description.clone(),content:String::new(),base:PathBuf::new(),model:c.invocation.model_invocable,user:c.invocation.user_invocable,definition:None,rank:c.rank,lazy:Some((provider.clone(),c))});}}candidates.sort_by(|a,b|a.rank.total_cmp(&b.rank));let mut entries=std::collections::BTreeMap::new();for e in candidates{entries.entry(e.name.clone()).or_insert(e);}Ok(entries.into_values().collect())}

 pub fn call(&self,roots:&[SkillRoot],args:&Value)->Result<Value,String>{Self::call_entries(self.merged(roots)?,args)}
 fn call_entries(entries:Vec<Entry>,args:&Value)->Result<Value,String>{let o=args.as_object().ok_or("arguments must be object")?;if o.len()!=1||!o.contains_key("name"){return Err("skill requires only name".into())}let name=args["name"].as_str().ok_or("name must be string")?;if !valid_name(name){return Err(format!("invalid skill name \"{name}\""))}let e=entries.into_iter().find(|e|e.name==name).ok_or_else(||format!("skill \"{name}\" is unknown or no longer available"))?;if !e.model{return Err(format!("skill \"{name}\" is not available for model invocation"))}if let Some((p,c))=&e.lazy{let skill=p.get(c)?.ok_or_else(||format!("skill \"{}\" is unknown or no longer available",e.name))?;if skill.name!=e.name{return Err(format!("skill \"{}\" is unknown or no longer available",e.name))}if !skill.invocation.model_invocable{return Err(format!("skill \"{}\" is not available for model invocation",e.name))}if !valid_name(&skill.name)||skill.description.is_empty(){return Err("invalid loaded skill definition".into())}Ok(value(&entry_runtime(&skill)))}else{Ok(value(&e))} }
 pub fn user_names(&self,roots:&[SkillRoot])->Result<Vec<String>,String>{Ok(self.merged(roots)?.into_iter().filter(|e|e.user).map(|e|e.name).collect())}
 pub fn direct(&self,roots:&[SkillRoot],text:&str)->Result<Vec<Value>,String>{let names=gestures(text);if names.is_empty(){return Ok(vec![])}let entries=self.merged(roots)?;Ok(names.iter().filter_map(|name|entries.iter().find(|e|&e.name==name&&e.user)).map(load_user).collect::<Result<Vec<_>,_>>()?.into_iter().flatten().collect())}
 pub fn catalog(&self,roots:&[SkillRoot])->Result<Value,String>{Ok(Value::Array(self.merged(roots)?.into_iter().filter(|e|e.model).map(|e|json!({"name":e.name,"description":catalog_description(&e.description)})).collect()))}
}
fn catalog_description(text:&str)->String{let normalized=text.split_whitespace().collect::<Vec<_>>().join(" ");if normalized.encode_utf16().count()>500{format!("{}...",normalized.chars().scan(0,|units,c|{*units+=c.len_utf16();(*units<=497).then_some(c)}).collect::<String>())}else{normalized}}
#[derive(Clone)]pub struct Candidate{pub name:String,pub description:String,pub provider:String,pub source:String,pub rank:f64,pub invocation:Invocation,pub locator:Value}
pub struct ProviderObservation{pub candidates:Vec<Candidate>,pub complete:bool}
pub trait SkillProvider:Send+Sync{fn name(&self)->&str;fn list(&self)->Result<ProviderObservation,String>;fn get(&self,candidate:&Candidate)->Result<Option<RuntimeSkill>,String>;}

fn entry_runtime(skill:&RuntimeSkill)->Entry{let mut v=json!({"name":skill.name,"provider":skill.provider,"content":skill.content});if let Some(base)=&skill.resource_base{v["resourceBase"]=base.clone();}Entry{name:skill.name.clone(),description:skill.description.clone(),content:skill.content.clone(),base:PathBuf::new(),model:skill.invocation.model_invocable,user:skill.invocation.user_invocable,definition:Some(v),rank:250.0,lazy:None}}
fn validate_candidate(c:&Candidate,provider:&str)->Result<(),String>{if !valid_name(&c.name)||c.description.is_empty()||!c.rank.is_finite()||c.provider!=provider{return Err("invalid provider skill candidate".into())}Ok(())}
fn load(e:&Entry)->Result<Value,String>{if let Some((p,c))=&e.lazy{let skill=p.get(c)?.ok_or_else(||format!("skill \"{}\" is unknown or no longer available",e.name))?;if !valid_name(&skill.name)||skill.description.is_empty(){return Err("invalid loaded skill definition".into())}if skill.name!=e.name{return Err(format!("skill \"{}\" is unknown or no longer available",e.name))}Ok(value(&entry_runtime(&skill)))}else{Ok(value(e))}}

fn load_user(e:&Entry)->Result<Option<Value>,String>{if let Some((p,c))=&e.lazy{let Some(skill)=p.get(c)?else{return Ok(None)};if !valid_name(&skill.name)||skill.description.is_empty(){return Err("invalid loaded skill definition".into())}if skill.name!=e.name||!skill.invocation.user_invocable{return Ok(None)}Ok(Some(value(&entry_runtime(&skill))))}else{Ok(Some(value(e)))}}
