//! Native dsh filesystem skill discovery. Roots are session-owned, never process overrides.
use std::path::{Path,PathBuf};use serde_json::{json,Value};
#[derive(Clone)]pub struct SkillRoot{pub path:PathBuf,pub rank:u32,pub skip_system:bool}
#[derive(Clone)]struct Entry{name:String,description:String,content:String,base:PathBuf,model:bool}
pub fn valid_name(s:&str)->bool{!s.is_empty()&&s.split('-').all(|p|!p.is_empty()&&p.bytes().all(|c|c.is_ascii_lowercase()||c.is_ascii_digit()))}
fn boolean(v:Option<&Value>)->Result<Option<bool>,String>{match v{None=>Ok(None),Some(Value::Bool(b))=>Ok(Some(*b)),Some(v)=>{let s=v.as_str().map(str::to_lowercase).unwrap_or_else(||v.to_string());match s.as_str(){"1"|"true"|"yes"|"on"=>Ok(Some(true)),"0"|"false"|"no"|"off"=>Ok(Some(false)),_=>Err("invalid invocation boolean".into())}}}}
fn parse(path:&Path,base:&Path)->Option<Entry>{let raw=std::fs::read_to_string(path).ok()?;let raw=raw.strip_prefix('\u{feff}').unwrap_or(&raw);let mut lines=raw.split_inclusive('\n');if lines.next()?.trim()!="---"{return None}let mut yaml=String::new();let mut offset=raw.find('\n')?+1;let mut closed=false;for line in lines{offset+=line.len();if matches!(line.trim(),"---"|"..."){closed=true;break}yaml.push_str(line);}if !closed{return None}let meta:Value=serde_yaml_ng::from_str(&yaml).ok()?;let name=meta["name"].as_str()?.to_owned();let description=meta["description"].as_str()?.to_owned();if !valid_name(&name)||description.is_empty(){return None}if ["disableModelInvocation","modelInvocable","userInvocable"].iter().any(|k|meta.get(k).is_some()){return None}let model=boolean(meta.get("disable-model-invocation")).ok()?!=Some(true);boolean(meta.get("user-invocable")).ok()?;Some(Entry{name,description,content:raw[offset..].trim().to_owned(),base:base.to_owned(),model})}
fn discover(roots:&[SkillRoot])->Result<Vec<Entry>,String>{let mut roots=roots.to_vec();roots.sort_by_key(|r|r.rank);let mut entries=std::collections::BTreeMap::new();for root in roots{let children=match std::fs::read_dir(&root.path){Ok(v)=>v,Err(e) if e.kind()==std::io::ErrorKind::NotFound=>continue,Err(e)=>return Err(format!("skill discovery {}: {e}",root.path.display()))};let mut children:Vec<_>=children.collect::<Result<_,_>>().map_err(|e|e.to_string())?;children.sort_by_key(|e|e.file_name());for child in children{if root.skip_system&&child.file_name()==".system"{continue}let p=child.path();let (file,base)=if p.is_dir(){(p.join("SKILL.md"),p)}else if p.extension().is_some_and(|s|s=="md"){(p,root.path.clone())}else{continue};if let Some(e)=parse(&file,&base){entries.entry(e.name.clone()).or_insert(e);}}}Ok(entries.into_values().collect())}
pub fn call(roots:&[SkillRoot],args:&Value)->Result<Value,String>{let o=args.as_object().ok_or("arguments must be object")?;if o.len()!=1||!o.contains_key("name"){return Err("skill requires only name".into())}let name=args["name"].as_str().ok_or("name must be string")?;if !valid_name(name){return Err(format!("invalid skill name \"{name}\""))}let e=discover(roots)?.into_iter().find(|e|e.name==name).ok_or_else(||format!("skill \"{name}\" is unknown or no longer available"))?;if !e.model{return Err(format!("skill \"{name}\" is not available for model invocation"))}Ok(json!({"name":e.name,"provider":"filesystem","resourceBase":{"kind":"directory","path":e.base},"content":e.content}))}
fn escaped(s:&str)->String{s.replace('&',"&amp;").replace('<',"&lt;").replace('>',"&gt;")}
pub fn render(v:&Value)->String{format!("<skill_content name=\"{}\">\n<skill_resources>\nBase directory for this skill: {}\nResolve relative paths mentioned by this skill against the base directory before using them. Load referenced resources only as needed.\n</skill_resources>\n\n<skill_instructions>\n{}\n</skill_instructions>\n</skill_content>",escaped(v["name"].as_str().unwrap_or("")).replace('"',"&quot;"),escaped(v["resourceBase"]["path"].as_str().unwrap_or("")),v["content"].as_str().unwrap_or(""))}
pub fn catalog(roots:&[SkillRoot])->Result<Value,String>{Ok(Value::Array(discover(roots)?.into_iter().filter(|e|e.model).map(|e|json!({"name":e.name,"description":({let normalized=e.description.split_whitespace().collect::<Vec<_>>().join(" ");if normalized.encode_utf16().count()>500{format!("{}...",normalized.chars().take(497).collect::<String>())}else{normalized}})})).collect()))}
pub fn project_roots(cwd:&Path)->Vec<SkillRoot>{let root=cwd.ancestors().find(|p|p.join(".git").exists()).unwrap_or(cwd);vec![SkillRoot{path:root.join(".dsh/skills"),rank:100,skip_system:false},SkillRoot{path:root.join(".agents/skills"),rank:200,skip_system:false}]}
pub fn catalog_text(entries:&Value,update:bool)->String{let lines=entries.as_array().into_iter().flatten().map(|e|format!("- `{}`: {}",e["name"].as_str().unwrap_or(""),escaped(e["description"].as_str().unwrap_or("")))).collect::<Vec<_>>().join("\n");if update{let availability=if entries.as_array().is_some_and(Vec::is_empty){"No skills are currently available through the `skill` tool. Do not use names from earlier skill catalogs.\nA user may still invoke a skill directly; its <skill_content> block then appears in this conversation. Follow it, and do not call the `skill` tool for it."}else{"Use only names in this replacement catalog. If the user names a listed skill, or the task clearly matches its description, call the `skill` tool with the exact name before acting.\nA user may also invoke a skill directly; its <skill_content> block then appears in this conversation. Follow it, and do not call the `skill` tool again for that skill."};format!("<system-reminder>\nThe available skill catalog changed. This complete catalog replaces every earlier available-skills list in this session:\n\n<available_skills>\n{lines}\n</available_skills>\n\n{availability}\n</system-reminder>")}else{format!("<system-reminder>\nA skill is a reusable set of task-specific instructions. The following skills are available in this session:\n\n<available_skills>\n{lines}\n</available_skills>\n\nIf the user names a skill, or the task clearly matches a skill's description, call the `skill` tool with the exact skill name before taking task actions. Load all applicable skills, then follow their full instructions. This catalog contains summaries only; do not infer or follow a skill's instructions until it has been loaded.\nA user may also invoke a skill directly; its <skill_content> block then appears in this conversation. Follow it, and do not call the `skill` tool again for that skill.\n</system-reminder>")}}
#[derive(Clone,serde::Deserialize)]#[serde(default,deny_unknown_fields,rename_all="camelCase")]pub struct RootConfig{pub include_default_roots:bool,pub dsh_home:Option<PathBuf>,pub agents_home:Option<PathBuf>,pub custom_skill_dirs:Vec<PathBuf>,pub bundled_skill_dir:Option<PathBuf>}
impl Default for RootConfig{fn default()->Self{Self{include_default_roots:true,dsh_home:None,agents_home:None,custom_skill_dirs:vec![],bundled_skill_dir:None}}}
impl RootConfig{pub fn roots(&self,project:Option<&Path>)->Vec<SkillRoot>{let home=std::env::var_os("HOME").map(PathBuf::from);let mut roots=if self.include_default_roots{project.map(project_roots).unwrap_or_default()}else{vec![]};roots.extend(self.custom_skill_dirs.iter().map(|p|SkillRoot{path:p.clone(),rank:300,skip_system:false}));if self.include_default_roots{if let Some(p)=self.dsh_home.clone().or_else(||home.as_ref().map(|h|h.join(".dsh"))){roots.push(SkillRoot{path:p.join("skills"),rank:400,skip_system:true});}if let Some(p)=self.agents_home.clone().or_else(||home.as_ref().map(|h|h.join(".agents"))){roots.push(SkillRoot{path:p.join("skills"),rank:500,skip_system:false});}}if let Some(p)=self.bundled_skill_dir.clone(){roots.push(SkillRoot{path:p,rank:600,skip_system:false});}roots}}
