//! Native path/content search using ripgrep argv, never a shell.
use serde_json::{json,Value};use std::path::{Path,PathBuf};use std::io::Read;use std::os::unix::process::CommandExt;
fn args(root:&Path,a:&Value,allowed:&[&str])->Result<(PathBuf,PathBuf,String),String>{let o=a.as_object().ok_or("arguments must be object")?;for k in o.keys(){if !allowed.contains(&k.as_str()){return Err(format!("unknown argument {k}"))}}let pattern=a["pattern"].as_str().filter(|s|!s.trim().is_empty()).ok_or("pattern must be nonblank string")?;let root=root.canonicalize().map_err(|e|e.to_string())?;let target=match a.get("path"){None=>root.clone(),Some(v)=>{let s=v.as_str().filter(|s|!s.trim().is_empty()).ok_or("path must be nonblank string")?;let p=Path::new(s);if p.is_absolute(){p.to_path_buf()}else{root.join(p)}}}.canonicalize().map_err(|e|e.to_string())?;if !target.starts_with(&root){return Err("sandbox: file access denied outside workspace".into())}Ok((root,target,pattern.into()))}
const RAW_CAP:usize=20_000_000;
fn capture(mut r:impl Read)->Result<(Vec<u8>,bool),String>{let mut data=vec![];let mut buf=[0;8192];let mut overflow=false;loop{let n=r.read(&mut buf).map_err(|e|e.to_string())?;if n==0{break}let keep=n.min(RAW_CAP.saturating_sub(data.len()));data.extend_from_slice(&buf[..keep]);overflow|=keep<n;}Ok((data,overflow))}
fn run(root:&Path,argv:&[String])->Result<String,String>{let mut c=std::process::Command::new("rg").arg("--no-config").args(argv).current_dir(root).env_remove("RIPGREP_CONFIG_PATH").stdout(std::process::Stdio::piped()).stderr(std::process::Stdio::piped()).process_group(0).spawn().map_err(|e|format!("SEARCH_FAILED: {e}"))?;let out=c.stdout.take().unwrap();let err=c.stderr.take().unwrap();let a=std::thread::spawn(move||capture(out));let b=std::thread::spawn(move||capture(err));let start=std::time::Instant::now();let status=loop{if let Some(s)=c.try_wait().map_err(|e|e.to_string())?{break s}if start.elapsed().as_secs()>=30{let _=std::process::Command::new("kill").args(["-KILL","--",&format!("-{}",c.id())]).status();let _=c.wait();let _=a.join();let _=b.join();return Err("SEARCH_ABORTED: search tool exceeded 30000ms".into())}std::thread::sleep(std::time::Duration::from_millis(5));};let(out,overflow)=a.join().map_err(|_|"SEARCH_FAILED: stdout worker")??;let(err,_)=b.join().map_err(|_|"SEARCH_FAILED: stderr worker")??;if overflow{return Err("SEARCH_RAW_OUTPUT_OVERFLOW: narrow pattern, path, or include and retry".into())}if !matches!(status.code(),Some(0)|Some(1)){let text=String::from_utf8_lossy(&err);let code=if text.contains("regex parse error")||text.contains("error parsing glob"){"SEARCH_INVALID_PATTERN"}else{"SEARCH_FAILED"};return Err(format!("{code}: {text}"))}String::from_utf8(out).map_err(|e|format!("SEARCH_FAILED: {e}"))}
fn display(root:&Path,p:&str)->String{let p=Path::new(p);p.strip_prefix(root).unwrap_or(p).to_string_lossy().into_owned()}
pub fn glob(root:&Path,a:&Value)->Result<Value,String>{let(root,target,p)=args(root,a,&["pattern","path"])?;if !target.is_dir(){return Err("glob path must be directory".into())}let mut argv=vec!["--files".into(),format!("--glob={p}"),"--sort=modified".into(),"--no-ignore".into(),"--hidden".into()];for n in [".git",".svn",".hg",".bzr",".jj",".sl"]{argv.push(format!("--glob=!**/{n}"));argv.push(format!("--glob=!**/{n}/**"));}argv.extend(["--".into(),target.to_string_lossy().into_owned()]);let all=run(&root,&argv)?.lines().filter(|s|!s.is_empty()).map(|s|display(&root,s)).collect::<Vec<_>>();Ok(json!({"root":display(&root,&target.to_string_lossy()),"paths":all}))}
pub fn grep(root:&Path,a:&Value)->Result<Value,String>{let(root,target,p)=args(root,a,&["pattern","path","include"])?;let mut argv=vec!["--json".into(),format!("--regexp={p}")];if let Some(v)=a.get("include"){let s=v.as_str().filter(|s|!s.trim().is_empty()&&!s.starts_with('!')).ok_or("include must be one nonnegative glob string")?;argv.push(format!("--glob={s}"))}argv.extend(["--".into(),target.to_string_lossy().into_owned()]);let mut all=vec![];for line in run(&root,&argv)?.lines(){let v:Value=serde_json::from_str(line).map_err(|e|format!("SEARCH_FAILED: malformed rg output: {e}"))?;if v["type"]!="match"{continue}let d=&v["data"];let path=d["path"]["text"].as_str().ok_or("SEARCH_FAILED: no path text")?;let n=d["line_number"].as_u64().ok_or("SEARCH_FAILED: no line number")?;let text=d["lines"]["text"].as_str().unwrap_or("[non-UTF8 line]").trim_end_matches(['\r','\n']);all.push(json!({"path":display(&root,path),"lineNumber":n,"line":text}));}Ok(json!({"matches":all}))}
fn spill(root:&Path,text:&str)->Result<PathBuf,String>{let mut dir=root.canonicalize().map_err(|e|e.to_string())?;for name in [".hs","search"]{dir.push(name);match std::fs::symlink_metadata(&dir){Ok(m) if m.file_type().is_symlink()||!m.is_dir()=>return Err("spill directory must not be symlink".into()),Ok(_)=>{},Err(e) if e.kind()==std::io::ErrorKind::NotFound=>std::fs::create_dir(&dir).map_err(|e|e.to_string())?,Err(e)=>return Err(e.to_string())}}let p=dir.join(format!("{}.txt",uuid::Uuid::new_v4()));use std::io::Write;let mut f=std::fs::OpenOptions::new().create_new(true).write(true).open(&p).map_err(|e|e.to_string())?;f.write_all(text.as_bytes()).map_err(|e|e.to_string())?;Ok(p)}
fn groups(matches:&[Value])->String{let mut groups:Vec<(String,Vec<String>)>=vec![];for m in matches{let p=m["path"].as_str().unwrap_or("");let line=format!("Line {}: {}",m["lineNumber"],preview(m["line"].as_str().unwrap_or("")));if let Some((_,lines))=groups.iter_mut().find(|(name,_)|name==p){lines.push(line)}else{groups.push((p.into(),vec![line]))}}groups.into_iter().map(|(p,l)|format!("{p}\n{}",l.join("\n"))).collect::<Vec<_>>().join("\n\n")}
pub fn render(root:&Path,tool:&str,v:&Value)->Result<String,String>{if tool=="glob"{let paths=v["paths"].as_array().ok_or("glob paths missing")?;if paths.is_empty(){return Ok("No files found".into())}let all=paths.iter().map(|p|p.as_str().unwrap_or("")).collect::<Vec<_>>();let body=all[..all.len().min(100)].join("\n");if all.len()<=100{return Ok(body)}let recovery=match spill(root,&all.join("\n")){Ok(p)=>format!("Full sorted result stored at: {}. Read the file to retrieve the complete result.",p.display()),Err(_)=>"The complete result could not be saved; narrow pattern or path to see more.".into()};Ok(format!("{body}\n\n(Showing 100 of {} paths. {recovery})",all.len()))}else{let matches=v["matches"].as_array().ok_or("grep matches missing")?;if matches.is_empty(){return Ok("No matches found".into())}let body=groups(&matches[..matches.len().min(250)]);if matches.len()<=250{return Ok(format!("Found {} {}\n\n{body}",matches.len(),if matches.len()==1{"match"}else{"matches"}))}let recovery=match spill(root,&groups(matches)){Ok(p)=>format!("Full grep result stored at: {}. Read the file to retrieve the complete result.",p.display()),Err(_)=>"The complete result could not be saved; narrow pattern, path, or include to see more.".into()};Ok(format!("Found 250 of {} matches\n\n{body}\n\n({recovery})",matches.len()))}}


fn preview(s:&str)->String{if s.len()<=2000{s.into()}else{format!("{} (line truncated)",crate::msgfmt::prefix_bytes_safe(s,2000))}}
pub fn metadata(tool:&str,v:&Value)->Value{let(mut m,key)=if tool=="glob"{let paths=v["paths"].as_array().cloned().unwrap_or_default();(json!({"shape":"paths","paths":paths.iter().take(100).cloned().collect::<Vec<_>>(),"truncated":paths.len()>100,"total":paths.len()}),"paths")}else{let matches=v["matches"].as_array().cloned().unwrap_or_default();let mut files:Vec<Value>=vec![];for x in matches.iter().take(250){let p=x["path"].as_str().unwrap_or("");let item=json!({"lineNumber":x["lineNumber"],"line":preview(x["line"].as_str().unwrap_or(""))});if let Some(f)=files.iter_mut().find(|f|f["path"]==p){f["matches"].as_array_mut().unwrap().push(item)}else{files.push(json!({"path":p,"matches":[item]}))}}(json!({"shape":"matches","files":files,"truncated":matches.len()>250,"total":matches.len()}),"files")};if serde_json::to_vec(&m).expect("meta serializes").len()>65536{m["truncated"]=json!(true)}while serde_json::to_vec(&m).expect("meta serializes").len()>65536&&m[key].as_array().unwrap().len()>1{m[key].as_array_mut().unwrap().pop();m["truncated"]=json!(true)}m}

pub fn card_text(meta:&Value)->String{let total=meta["total"].as_u64().unwrap_or(0);let capped=if meta["truncated"]==true{" (truncated)"}else{""};let mut lines=vec![format!("Search: {total} {}{capped}",if meta["shape"]=="paths"{"paths"}else{"matches"})];if let Some(paths)=meta["paths"].as_array(){lines.extend(paths.iter().filter_map(|p|p.as_str().map(str::to_owned)))}if let Some(files)=meta["files"].as_array(){for f in files{lines.push(f["path"].as_str().unwrap_or("").into());if let Some(matches)=f["matches"].as_array(){for m in matches{lines.push(format!("Line {}: {}",m["lineNumber"],m["line"].as_str().unwrap_or("")));}}}}lines.join("\n")}
